// ai - AI integration library
// Provides native bounds for LLM APIs like Gemini and OpenAI

pub fn generate_ai_lib() -> String {
    let mut code = String::new();
    
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("\n");
    code.push_str("// Forward declarations from other standard libraries\n");
    code.push_str("char* json_escape(const char* s);\n");
    code.push_str("char* http_PostWithHeaders(const char* url, const char* data, const char* headers);\n");
    code.push_str("char* json_UnmarshalString(const char* json);\n");
    code.push_str("\n");
    code.push_str("// ai.GenerateTextGemini - Call Google Gemini Pro API\n");
    code.push_str("// api_key: Gemini API Key\n");
    code.push_str("// prompt: Input text prompt\n");
    code.push_str("// Returns: Generated response text (caller must free), or NULL on error\n");
    code.push_str("char* ai_GenerateTextGemini(const char* api_key, const char* prompt) {\n");
    code.push_str("    if (!api_key || !prompt) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    char url[512];\n");
    code.push_str("    snprintf(url, sizeof(url), \"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=%s\", api_key);\n");
    code.push_str("    \n");
    code.push_str("    char* escaped_prompt = json_escape(prompt);\n");
    code.push_str("    char payload[8192];\n");
    code.push_str("    snprintf(payload, sizeof(payload), \"{\\\"contents\\\":[{\\\"parts\\\":[{\\\"text\\\":%s}]}]}\", escaped_prompt);\n");
    code.push_str("    \n");
    code.push_str("    const char* headers = \"Content-Type: application/json\\r\\n\";\n");
    code.push_str("    char* response = http_PostWithHeaders(url, payload, headers);\n");
    code.push_str("    if (!response) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Parse response - very simplified extraction due to nested structure\n");
    code.push_str("    // Expecting: {...,\"text\": \"response text\",...}\n");
    code.push_str("    char* text_field = strstr(response, \"\\\"text\\\":\");\n");
    code.push_str("    if (!text_field) {\n");
    code.push_str("        return response; // Return raw json if text field not found\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    text_field += 7; // skip \"text\":\n");
    code.push_str("    while (*text_field == ' ' || *text_field == '\\t') text_field++; // skip whitespace\n");
    code.push_str("    \n");
    code.push_str("    // use json_UnmarshalString to extract value\n");
    code.push_str("    char* result = json_UnmarshalString(text_field);\n");
    code.push_str("    free(response);\n");
    code.push_str("    if (result) return result;\n");
    code.push_str("    \n");
    code.push_str("    return NULL;\n");
    code.push_str("}\n\n");
    
    code.push_str("// ai.GenerateTextOpenAI - Call OpenAI Chat Completions API\n");
    code.push_str("// api_key: OpenAI API Key\n");
    code.push_str("// prompt: Input text prompt\n");
    code.push_str("// Returns: Generated response text (caller must free), or NULL on error\n");
    code.push_str("char* ai_GenerateTextOpenAI(const char* api_key, const char* prompt) {\n");
    code.push_str("    if (!api_key || !prompt) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    const char* url = \"https://api.openai.com/v1/chat/completions\";\n");
    code.push_str("    \n");
    code.push_str("    char headers[512];\n");
    code.push_str("    snprintf(headers, sizeof(headers), \"Content-Type: application/json\\r\\nAuthorization: Bearer %s\\r\\n\", api_key);\n");
    code.push_str("    \n");
    code.push_str("    char* escaped_prompt = json_escape(prompt);\n");
    code.push_str("    char payload[8192];\n");
    code.push_str("    snprintf(payload, sizeof(payload), \"{\\\"model\\\":\\\"gpt-3.5-turbo\\\",\\\"messages\\\":[{\\\"role\\\":\\\"user\\\",\\\"content\\\":%s}]}\", escaped_prompt);\n");
    code.push_str("    \n");
    code.push_str("    char* response = http_PostWithHeaders(url, payload, headers);\n");
    code.push_str("    if (!response) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Parse response - very simplified extraction\n");
    code.push_str("    char* content_field = strstr(response, \"\\\"content\\\":\");\n");
    code.push_str("    if (!content_field) {\n");
    code.push_str("        return response; // Return raw json if parsing fails\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    content_field += 10; // skip \"content\":\n");
    code.push_str("    while (*content_field == ' ' || *content_field == '\\t') content_field++; // skip whitespace\n");
    code.push_str("    \n");
    code.push_str("    char* result = json_UnmarshalString(content_field);\n");
    code.push_str("    free(response);\n");
    code.push_str("    if (result) return result;\n");
    code.push_str("    \n");
    code.push_str("    return NULL;\n");
    code.push_str("}\n\n");
    
    code.push_str("// ai.GenerateTextClaude - Call Anthropic Claude API\n");
    code.push_str("// api_key: Anthropic API Key\n");
    code.push_str("// prompt: Input text prompt\n");
    code.push_str("// Returns: Generated response text (caller must free), or NULL on error\n");
    code.push_str("char* ai_GenerateTextClaude(const char* api_key, const char* prompt) {\n");
    code.push_str("    if (!api_key || !prompt) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    const char* url = \"https://api.anthropic.com/v1/messages\";\n");
    code.push_str("    \n");
    code.push_str("    char headers[512];\n");
    code.push_str("    snprintf(headers, sizeof(headers), \"Content-Type: application/json\\r\\nx-api-key: %s\\r\\nanthropic-version: 2023-06-01\\r\\n\", api_key);\n");
    code.push_str("    \n");
    code.push_str("    char* escaped_prompt = json_escape(prompt);\n");
    code.push_str("    char payload[8192];\n");
    code.push_str("    snprintf(payload, sizeof(payload), \"{\\\"model\\\":\\\"claude-3-haiku-20240307\\\",\\\"max_tokens\\\":1024,\\\"messages\\\":[{\\\"role\\\":\\\"user\\\",\\\"content\\\":%s}]}\", escaped_prompt);\n");
    code.push_str("    \n");
    code.push_str("    char* response = http_PostWithHeaders(url, payload, headers);\n");
    code.push_str("    if (!response) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Parse response - look for \"text\":\n");
    code.push_str("    char* text_field = strstr(response, \"\\\"text\\\":\");\n");
    code.push_str("    if (!text_field) {\n");
    code.push_str("        return response; // Return raw json if parsing fails\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    text_field += 7; // skip \"text\":\n");
    code.push_str("    while (*text_field == ' ' || *text_field == '\\t') text_field++; // skip whitespace\n");
    code.push_str("    \n");
    code.push_str("    char* result = json_UnmarshalString(text_field);\n");
    code.push_str("    free(response);\n");
    code.push_str("    if (result) return result;\n");
    code.push_str("    \n");
    code.push_str("    return NULL;\n");
    code.push_str("}\n\n");
    
    code
}
