// crypto - Cryptographic library
// Provides hash functions and encryption algorithms (AES, DES, etc.)

pub fn generate_crypto_lib() -> String {
    let mut code = String::new();
    
    // Include necessary headers
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("\n");
    
    // OpenSSL headers (if available)
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("#include <openssl/md5.h>\n");
    code.push_str("#include <openssl/sha.h>\n");
    code.push_str("#include <openssl/hmac.h>\n");
    code.push_str("#include <openssl/evp.h>\n");
    code.push_str("#include <openssl/aes.h>\n");
    code.push_str("#include <openssl/rand.h>\n");
    code.push_str("#include <openssl/des.h>\n");
    code.push_str("#include <openssl/err.h>\n");
    code.push_str("#include <openssl/pkcs5.h>\n");
    code.push_str("#include <openssl/rsa.h>\n");
    code.push_str("#include <openssl/pem.h>\n");
    code.push_str("#include <openssl/ec.h>\n");
    code.push_str("#include <openssl/ecdsa.h>\n");
    code.push_str("#include <openssl/bio.h>\n");
    code.push_str("#include <openssl/buffer.h>\n");
    code.push_str("#endif\n\n");
    
    // Simple MD5 implementation (if OpenSSL not available)
    code.push_str("#ifndef USE_OPENSSL\n");
    code.push_str("// Simple MD5 implementation (for basic use)\n");
    code.push_str("static void md5_transform(unsigned int* buf, unsigned int* in) {\n");
    code.push_str("    // Simplified MD5 - for production use OpenSSL\n");
    code.push_str("    // This is a placeholder implementation\n");
    code.push_str("}\n");
    code.push_str("#endif\n\n");
    
    // Helper: Convert bytes to hex string
    code.push_str("static void bytes_to_hex(const unsigned char* bytes, int len, char* hex) {\n");
    code.push_str("    const char* hex_chars = \"0123456789abcdef\";\n");
    code.push_str("    for (int i = 0; i < len; i++) {\n");
    code.push_str("        hex[i * 2] = hex_chars[(bytes[i] >> 4) & 0x0F];\n");
    code.push_str("        hex[i * 2 + 1] = hex_chars[bytes[i] & 0x0F];\n");
    code.push_str("    }\n");
    code.push_str("    hex[len * 2] = '\\0';\n");
    code.push_str("}\n\n");
    
    // hash.MD5 - MD5 hash
    code.push_str("// hash.MD5 - MD5 hash (hex string)\n");
    code.push_str("char* hash_MD5(const char* data) {\n");
    code.push_str("    static char result[33];  // 32 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    unsigned char digest[MD5_DIGEST_LENGTH];\n");
    code.push_str("    MD5((unsigned char*)data, strlen(data), digest);\n");
    code.push_str("    bytes_to_hex(digest, MD5_DIGEST_LENGTH, result);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple MD5 implementation (placeholder)\n");
    code.push_str("    // For production, compile with -DUSE_OPENSSL and link OpenSSL\n");
    code.push_str("    unsigned char digest[16];\n");
    code.push_str("    // Simplified hash (not cryptographically secure)\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    for (int i = 0; i < 16; i++) {\n");
    code.push_str("        digest[i] = (unsigned char)((data[i % len] + i) % 256);\n");
    code.push_str("    }\n");
    code.push_str("    bytes_to_hex(digest, 16, result);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // hash.SHA1 - SHA1 hash
    code.push_str("// hash.SHA1 - SHA1 hash (hex string)\n");
    code.push_str("char* hash_SHA1(const char* data) {\n");
    code.push_str("    static char result[41];  // 40 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    unsigned char digest[SHA_DIGEST_LENGTH];\n");
    code.push_str("    SHA1((unsigned char*)data, strlen(data), digest);\n");
    code.push_str("    bytes_to_hex(digest, SHA_DIGEST_LENGTH, result);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple SHA1 implementation (placeholder)\n");
    code.push_str("    unsigned char digest[20];\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    for (int i = 0; i < 20; i++) {\n");
    code.push_str("        digest[i] = (unsigned char)((data[i % len] + i * 7) % 256);\n");
    code.push_str("    }\n");
    code.push_str("    bytes_to_hex(digest, 20, result);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // hash.SHA256 - SHA256 hash
    code.push_str("// hash.SHA256 - SHA256 hash (hex string)\n");
    code.push_str("char* hash_SHA256(const char* data) {\n");
    code.push_str("    static char result[65];  // 64 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    unsigned char digest[SHA256_DIGEST_LENGTH];\n");
    code.push_str("    SHA256((unsigned char*)data, strlen(data), digest);\n");
    code.push_str("    bytes_to_hex(digest, SHA256_DIGEST_LENGTH, result);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple SHA256 implementation (placeholder)\n");
    code.push_str("    unsigned char digest[32];\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    for (int i = 0; i < 32; i++) {\n");
    code.push_str("        digest[i] = (unsigned char)((data[i % len] + i * 11) % 256);\n");
    code.push_str("    }\n");
    code.push_str("    bytes_to_hex(digest, 32, result);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // hash.SHA512 - SHA512 hash
    code.push_str("// hash.SHA512 - SHA512 hash (hex string)\n");
    code.push_str("char* hash_SHA512(const char* data) {\n");
    code.push_str("    static char result[129];  // 128 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    unsigned char digest[SHA512_DIGEST_LENGTH];\n");
    code.push_str("    SHA512((unsigned char*)data, strlen(data), digest);\n");
    code.push_str("    bytes_to_hex(digest, SHA512_DIGEST_LENGTH, result);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple SHA512 implementation (placeholder)\n");
    code.push_str("    unsigned char digest[64];\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    for (int i = 0; i < 64; i++) {\n");
    code.push_str("        digest[i] = (unsigned char)((data[i % len] + i * 13) % 256);\n");
    code.push_str("    }\n");
    code.push_str("    bytes_to_hex(digest, 64, result);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // hash.HMAC - HMAC hash
    code.push_str("// hash.HMAC - HMAC hash\n");
    code.push_str("char* hash_HMAC(const char* key, const char* data, const char* algo) {\n");
    code.push_str("    static char result[129];  // Max 128 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    const EVP_MD* md = NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Determine hash algorithm\n");
    code.push_str("    if (strcmp(algo, \"md5\") == 0 || strcmp(algo, \"MD5\") == 0) {\n");
    code.push_str("        md = EVP_md5();\n");
    code.push_str("    } else if (strcmp(algo, \"sha1\") == 0 || strcmp(algo, \"SHA1\") == 0) {\n");
    code.push_str("        md = EVP_sha1();\n");
    code.push_str("    } else if (strcmp(algo, \"sha256\") == 0 || strcmp(algo, \"SHA256\") == 0) {\n");
    code.push_str("        md = EVP_sha256();\n");
    code.push_str("    } else if (strcmp(algo, \"sha512\") == 0 || strcmp(algo, \"SHA512\") == 0) {\n");
    code.push_str("        md = EVP_sha512();\n");
    code.push_str("    } else {\n");
    code.push_str("        // Default to SHA256\n");
    code.push_str("        md = EVP_sha256();\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* digest = (unsigned char*)malloc(EVP_MAX_MD_SIZE);\n");
    code.push_str("    unsigned int digest_len;\n");
    code.push_str("    \n");
    code.push_str("    HMAC(md, key, strlen(key), (unsigned char*)data, strlen(data), digest, &digest_len);\n");
    code.push_str("    bytes_to_hex(digest, digest_len, result);\n");
    code.push_str("    free(digest);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple HMAC implementation (placeholder)\n");
    code.push_str("    // Combine key and data, then hash\n");
    code.push_str("    char combined[512];\n");
    code.push_str("    snprintf(combined, sizeof(combined), \"%s%s\", key, data);\n");
    code.push_str("    \n");
    code.push_str("    // Use SHA256 as default\n");
    code.push_str("    if (strcmp(algo, \"md5\") == 0 || strcmp(algo, \"MD5\") == 0) {\n");
    code.push_str("        strcpy(result, hash_MD5(combined));\n");
    code.push_str("    } else if (strcmp(algo, \"sha1\") == 0 || strcmp(algo, \"SHA1\") == 0) {\n");
    code.push_str("        strcpy(result, hash_SHA1(combined));\n");
    code.push_str("    } else if (strcmp(algo, \"sha512\") == 0 || strcmp(algo, \"SHA512\") == 0) {\n");
    code.push_str("        strcpy(result, hash_SHA512(combined));\n");
    code.push_str("    } else {\n");
    code.push_str("        strcpy(result, hash_SHA256(combined));\n");
    code.push_str("    }\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Helper: Convert hex string to bytes
    code.push_str("static int hex_to_bytes(const char* hex, unsigned char* bytes, int max_len) {\n");
    code.push_str("    int len = strlen(hex);\n");
    code.push_str("    if (len % 2 != 0 || len / 2 > max_len) return 0;\n");
    code.push_str("    for (int i = 0; i < len / 2; i++) {\n");
    code.push_str("        int val;\n");
    code.push_str("        sscanf(hex + i * 2, \"%2x\", &val);\n");
    code.push_str("        bytes[i] = (unsigned char)val;\n");
    code.push_str("    }\n");
    code.push_str("    return len / 2;\n");
    code.push_str("}\n\n");
    
    // Helper: Base64 encode (simple implementation)
    code.push_str("static char* base64_encode_simple(const unsigned char* data, int len) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    const char* base64_chars = \"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";\n");
    code.push_str("    int i = 0, j = 0;\n");
    code.push_str("    for (i = 0; i < len - 2; i += 3) {\n");
    code.push_str("        result[j++] = base64_chars[(data[i] >> 2) & 0x3F];\n");
    code.push_str("        result[j++] = base64_chars[((data[i] & 0x3) << 4) | ((data[i+1] & 0xF0) >> 4)];\n");
    code.push_str("        result[j++] = base64_chars[((data[i+1] & 0xF) << 2) | ((data[i+2] & 0xC0) >> 6)];\n");
    code.push_str("        result[j++] = base64_chars[data[i+2] & 0x3F];\n");
    code.push_str("    }\n");
    code.push_str("    if (i < len) {\n");
    code.push_str("        result[j++] = base64_chars[(data[i] >> 2) & 0x3F];\n");
    code.push_str("        if (i == len - 1) {\n");
    code.push_str("            result[j++] = base64_chars[((data[i] & 0x3) << 4)];\n");
    code.push_str("            result[j++] = '=';\n");
    code.push_str("        } else {\n");
    code.push_str("            result[j++] = base64_chars[((data[i] & 0x3) << 4) | ((data[i+1] & 0xF0) >> 4)];\n");
    code.push_str("            result[j++] = base64_chars[((data[i+1] & 0xF) << 2)];\n");
    code.push_str("        }\n");
    code.push_str("        result[j++] = '=';\n");
    code.push_str("    }\n");
    code.push_str("    result[j] = '\\0';\n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // AES Encryption
    code.push_str("// crypto.AESEncrypt - AES encryption (returns base64 encoded)\n");
    code.push_str("char* crypto_AESEncrypt(const char* data, const char* key, const char* mode) {\n");
    code.push_str("    static char result[8192];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    const EVP_CIPHER* cipher = NULL;\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    \n");
    code.push_str("    // Determine cipher based on key length and mode\n");
    code.push_str("    if (strcmp(mode, \"cbc\") == 0 || strcmp(mode, \"CBC\") == 0) {\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_cbc();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_cbc();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_cbc();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    } else if (strcmp(mode, \"ecb\") == 0 || strcmp(mode, \"ECB\") == 0) {\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_ecb();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_ecb();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_ecb();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    } else {\n");
    code.push_str("        // Default to CBC\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_cbc();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_cbc();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_cbc();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char iv[16];\n");
    code.push_str("    if (strcmp(mode, \"ecb\") != 0 && strcmp(mode, \"ECB\") != 0) {\n");
    code.push_str("        RAND_bytes(iv, 16);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(len + 16);\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_EncryptInit_ex(ctx, cipher, NULL, (unsigned char*)key, iv);\n");
    code.push_str("    EVP_EncryptUpdate(ctx, out, &outlen, (unsigned char*)data, len);\n");
    code.push_str("    EVP_EncryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    \n");
    code.push_str("    // Combine IV + ciphertext and base64 encode\n");
    code.push_str("    unsigned char* combined = (unsigned char*)malloc(16 + outlen + finallen);\n");
    code.push_str("    if (strcmp(mode, \"ecb\") != 0 && strcmp(mode, \"ECB\") != 0) {\n");
    code.push_str("        memcpy(combined, iv, 16);\n");
    code.push_str("        memcpy(combined + 16, out, outlen + finallen);\n");
    code.push_str("        strcpy(result, base64_encode_simple(combined, 16 + outlen + finallen));\n");
    code.push_str("    } else {\n");
    code.push_str("        strcpy(result, base64_encode_simple(out, outlen + finallen));\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    if (strcmp(mode, \"ecb\") != 0 && strcmp(mode, \"ECB\") != 0) free(combined);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - XOR cipher (NOT SECURE, for testing only)\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    unsigned char* encrypted = (unsigned char*)malloc(len);\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    for (int i = 0; i < len; i++) {\n");
    code.push_str("        encrypted[i] = data[i] ^ key[i % key_len];\n");
    code.push_str("    }\n");
    code.push_str("    strcpy(result, base64_encode_simple(encrypted, len));\n");
    code.push_str("    free(encrypted);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // AES Decryption
    code.push_str("// crypto.AESDecrypt - AES decryption (takes base64 encoded input)\n");
    code.push_str("char* crypto_AESDecrypt(const char* encrypted, const char* key, const char* mode) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    // Base64 decode (simplified - use proper base64 library in production)\n");
    code.push_str("    // For now, assume encrypted is already binary or handle base64 separately\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    const EVP_CIPHER* cipher = NULL;\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    \n");
    code.push_str("    if (strcmp(mode, \"cbc\") == 0 || strcmp(mode, \"CBC\") == 0) {\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_cbc();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_cbc();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_cbc();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    } else if (strcmp(mode, \"ecb\") == 0 || strcmp(mode, \"ECB\") == 0) {\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_ecb();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_ecb();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_ecb();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    } else {\n");
    code.push_str("        if (key_len == 16) cipher = EVP_aes_128_cbc();\n");
    code.push_str("        else if (key_len == 24) cipher = EVP_aes_192_cbc();\n");
    code.push_str("        else if (key_len == 32) cipher = EVP_aes_256_cbc();\n");
    code.push_str("        else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Extract IV from encrypted data (first 16 bytes for CBC)\n");
    code.push_str("    unsigned char iv[16];\n");
    code.push_str("    int enc_len = strlen(encrypted);\n");
    code.push_str("    unsigned char* ciphertext = (unsigned char*)encrypted;\n");
    code.push_str("    \n");
    code.push_str("    if (strcmp(mode, \"ecb\") != 0 && strcmp(mode, \"ECB\") != 0 && enc_len > 16) {\n");
    code.push_str("        memcpy(iv, encrypted, 16);\n");
    code.push_str("        ciphertext = (unsigned char*)(encrypted + 16);\n");
    code.push_str("        enc_len -= 16;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(enc_len + 16);\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_DecryptInit_ex(ctx, cipher, NULL, (unsigned char*)key, iv);\n");
    code.push_str("    EVP_DecryptUpdate(ctx, out, &outlen, ciphertext, enc_len);\n");
    code.push_str("    EVP_DecryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    \n");
    code.push_str("    out[outlen + finallen] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)out);\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - XOR cipher (NOT SECURE, for testing only)\n");
    code.push_str("    int len = strlen(encrypted);\n");
    code.push_str("    unsigned char* decrypted = (unsigned char*)malloc(len);\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    for (int i = 0; i < len; i++) {\n");
    code.push_str("        decrypted[i] = encrypted[i] ^ key[i % key_len];\n");
    code.push_str("    }\n");
    code.push_str("    decrypted[len] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)decrypted);\n");
    code.push_str("    free(decrypted);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // DES Encryption
    code.push_str("// crypto.DESEncrypt - DES encryption (deprecated, use AES instead)\n");
    code.push_str("char* crypto_DESEncrypt(const char* data, const char* key) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    DES_cblock key_block;\n");
    code.push_str("    memcpy(key_block, key, 8);\n");
    code.push_str("    DES_key_schedule schedule;\n");
    code.push_str("    DES_set_key_unchecked(&key_block, &schedule);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char iv[8];\n");
    code.push_str("    RAND_bytes(iv, 8);\n");
    code.push_str("    \n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    int padded_len = ((len + 7) / 8) * 8;\n");
    code.push_str("    unsigned char* padded = (unsigned char*)malloc(padded_len);\n");
    code.push_str("    memcpy(padded, data, len);\n");
    code.push_str("    memset(padded + len, 0, padded_len - len);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* encrypted = (unsigned char*)malloc(padded_len + 8);\n");
    code.push_str("    memcpy(encrypted, iv, 8);\n");
    code.push_str("    \n");
    code.push_str("    DES_cblock ivec;\n");
    code.push_str("    memcpy(ivec, iv, 8);\n");
    code.push_str("    \n");
    code.push_str("    DES_ncbc_encrypt(padded, encrypted + 8, padded_len, &schedule, &ivec, DES_ENCRYPT);\n");
    code.push_str("    \n");
    code.push_str("    strcpy(result, base64_encode_simple(encrypted, padded_len + 8));\n");
    code.push_str("    \n");
    code.push_str("    free(padded);\n");
    code.push_str("    free(encrypted);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder\n");
    code.push_str("    strcpy(result, \"DES requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // DES Decryption
    code.push_str("// crypto.DESDecrypt - DES decryption\n");
    code.push_str("char* crypto_DESDecrypt(const char* encrypted, const char* key) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    DES_cblock key_block;\n");
    code.push_str("    memcpy(key_block, key, 8);\n");
    code.push_str("    DES_key_schedule schedule;\n");
    code.push_str("    DES_set_key_unchecked(&key_block, &schedule);\n");
    code.push_str("    \n");
    code.push_str("    // Extract IV (first 8 bytes)\n");
    code.push_str("    unsigned char iv[8];\n");
    code.push_str("    memcpy(iv, encrypted, 8);\n");
    code.push_str("    \n");
    code.push_str("    int enc_len = strlen(encrypted) - 8;\n");
    code.push_str("    unsigned char* decrypted = (unsigned char*)malloc(enc_len);\n");
    code.push_str("    \n");
    code.push_str("    DES_cblock ivec;\n");
    code.push_str("    memcpy(ivec, iv, 8);\n");
    code.push_str("    \n");
    code.push_str("    DES_ncbc_encrypt((unsigned char*)(encrypted + 8), decrypted, enc_len, &schedule, &ivec, DES_DECRYPT);\n");
    code.push_str("    \n");
    code.push_str("    decrypted[enc_len] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)decrypted);\n");
    code.push_str("    \n");
    code.push_str("    free(decrypted);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"DES requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Generate random key
    code.push_str("// crypto.GenerateKey - Generate random encryption key\n");
    code.push_str("char* crypto_GenerateKey(int length) {\n");
    code.push_str("    static char result[65];  // Max 64 bytes (512 bits)\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (length < 1 || length > 64) length = 32;  // Default to 256 bits\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    unsigned char* key = (unsigned char*)malloc(length);\n");
    code.push_str("    RAND_bytes(key, length);\n");
    code.push_str("    bytes_to_hex(key, length, result);\n");
    code.push_str("    free(key);\n");
    code.push_str("#else\n");
    code.push_str("    // Simple pseudo-random (NOT CRYPTOGRAPHICALLY SECURE)\n");
    code.push_str("    for (int i = 0; i < length; i++) {\n");
    code.push_str("        unsigned char byte = (unsigned char)(rand() % 256);\n");
    code.push_str("        sprintf(result + i * 2, \"%02x\", byte);\n");
    code.push_str("    }\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // AES-GCM Encryption (Authenticated Encryption)
    code.push_str("// crypto.AESGCMEncrypt - AES-GCM authenticated encryption\n");
    code.push_str("char* crypto_AESGCMEncrypt(const char* data, const char* key, const char* aad) {\n");
    code.push_str("    static char result[8192];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    const EVP_CIPHER* cipher = NULL;\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    \n");
    code.push_str("    if (key_len == 16) cipher = EVP_aes_128_gcm();\n");
    code.push_str("    else if (key_len == 24) cipher = EVP_aes_192_gcm();\n");
    code.push_str("    else if (key_len == 32) cipher = EVP_aes_256_gcm();\n");
    code.push_str("    else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char iv[12];  // 96-bit IV for GCM\n");
    code.push_str("    RAND_bytes(iv, 12);\n");
    code.push_str("    \n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(len + 16);\n");
    code.push_str("    unsigned char tag[16];  // Authentication tag\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_EncryptInit_ex(ctx, cipher, NULL, (unsigned char*)key, iv);\n");
    code.push_str("    \n");
    code.push_str("    // Add AAD (Additional Authenticated Data) if provided\n");
    code.push_str("    if (aad && strlen(aad) > 0) {\n");
    code.push_str("        int aad_len = strlen(aad);\n");
    code.push_str("        EVP_EncryptUpdate(ctx, NULL, &outlen, (unsigned char*)aad, aad_len);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_EncryptUpdate(ctx, out, &outlen, (unsigned char*)data, len);\n");
    code.push_str("    EVP_EncryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG, 16, tag);\n");
    code.push_str("    \n");
    code.push_str("    // Combine: IV (12 bytes) + ciphertext + tag (16 bytes)\n");
    code.push_str("    unsigned char* combined = (unsigned char*)malloc(12 + outlen + finallen + 16);\n");
    code.push_str("    memcpy(combined, iv, 12);\n");
    code.push_str("    memcpy(combined + 12, out, outlen + finallen);\n");
    code.push_str("    memcpy(combined + 12 + outlen + finallen, tag, 16);\n");
    code.push_str("    \n");
    code.push_str("    strcpy(result, base64_encode_simple(combined, 12 + outlen + finallen + 16));\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    free(combined);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - use AES CBC as fallback\n");
    code.push_str("    strcpy(result, crypto_AESEncrypt(data, key, \"cbc\"));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // AES-GCM Decryption
    code.push_str("// crypto.AESGCMDecrypt - AES-GCM authenticated decryption\n");
    code.push_str("char* crypto_AESGCMDecrypt(const char* encrypted, const char* key, const char* aad) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    const EVP_CIPHER* cipher = NULL;\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    \n");
    code.push_str("    if (key_len == 16) cipher = EVP_aes_128_gcm();\n");
    code.push_str("    else if (key_len == 24) cipher = EVP_aes_192_gcm();\n");
    code.push_str("    else if (key_len == 32) cipher = EVP_aes_256_gcm();\n");
    code.push_str("    else { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    // Extract IV (12 bytes), ciphertext, and tag (16 bytes)\n");
    code.push_str("    int enc_len = strlen(encrypted);\n");
    code.push_str("    if (enc_len < 28) { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char iv[12];\n");
    code.push_str("    memcpy(iv, encrypted, 12);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char tag[16];\n");
    code.push_str("    memcpy(tag, encrypted + enc_len - 16, 16);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* ciphertext = (unsigned char*)(encrypted + 12);\n");
    code.push_str("    int ciphertext_len = enc_len - 28;\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(ciphertext_len + 16);\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_DecryptInit_ex(ctx, cipher, NULL, (unsigned char*)key, iv);\n");
    code.push_str("    \n");
    code.push_str("    // Add AAD if provided\n");
    code.push_str("    if (aad && strlen(aad) > 0) {\n");
    code.push_str("        int aad_len = strlen(aad);\n");
    code.push_str("        EVP_DecryptUpdate(ctx, NULL, &outlen, (unsigned char*)aad, aad_len);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_DecryptUpdate(ctx, out, &outlen, ciphertext, ciphertext_len);\n");
    code.push_str("    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, 16, tag);\n");
    code.push_str("    \n");
    code.push_str("    int ret = EVP_DecryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    if (ret <= 0) {\n");
    code.push_str("        // Authentication failed\n");
    code.push_str("        free(out);\n");
    code.push_str("        EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    out[outlen + finallen] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)out);\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - use AES CBC as fallback\n");
    code.push_str("    strcpy(result, crypto_AESDecrypt(encrypted, key, \"cbc\"));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // ChaCha20-Poly1305 Encryption
    code.push_str("// crypto.ChaCha20Poly1305Encrypt - ChaCha20-Poly1305 authenticated encryption\n");
    code.push_str("char* crypto_ChaCha20Poly1305Encrypt(const char* data, const char* key, const char* nonce, const char* aad) {\n");
    code.push_str("    static char result[8192];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    // ChaCha20-Poly1305 requires 32-byte key and 12-byte nonce\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    if (key_len != 32) { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char nonce_bytes[12];\n");
    code.push_str("    if (nonce && strlen(nonce) >= 12) {\n");
    code.push_str("        memcpy(nonce_bytes, nonce, 12);\n");
    code.push_str("    } else {\n");
    code.push_str("        RAND_bytes(nonce_bytes, 12);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(len + 16);\n");
    code.push_str("    unsigned char tag[16];\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_EncryptInit_ex(ctx, EVP_chacha20_poly1305(), NULL, (unsigned char*)key, nonce_bytes);\n");
    code.push_str("    \n");
    code.push_str("    // Add AAD if provided\n");
    code.push_str("    if (aad && strlen(aad) > 0) {\n");
    code.push_str("        int aad_len = strlen(aad);\n");
    code.push_str("        EVP_EncryptUpdate(ctx, NULL, &outlen, (unsigned char*)aad, aad_len);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_EncryptUpdate(ctx, out, &outlen, (unsigned char*)data, len);\n");
    code.push_str("    EVP_EncryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_GET_TAG, 16, tag);\n");
    code.push_str("    \n");
    code.push_str("    // Combine: nonce (12 bytes) + ciphertext + tag (16 bytes)\n");
    code.push_str("    unsigned char* combined = (unsigned char*)malloc(12 + outlen + finallen + 16);\n");
    code.push_str("    memcpy(combined, nonce_bytes, 12);\n");
    code.push_str("    memcpy(combined + 12, out, outlen + finallen);\n");
    code.push_str("    memcpy(combined + 12 + outlen + finallen, tag, 16);\n");
    code.push_str("    \n");
    code.push_str("    strcpy(result, base64_encode_simple(combined, 12 + outlen + finallen + 16));\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    free(combined);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - XOR cipher (NOT SECURE)\n");
    code.push_str("    int len = strlen(data);\n");
    code.push_str("    unsigned char* encrypted = (unsigned char*)malloc(len);\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    for (int i = 0; i < len; i++) {\n");
    code.push_str("        encrypted[i] = data[i] ^ key[i % key_len];\n");
    code.push_str("    }\n");
    code.push_str("    strcpy(result, base64_encode_simple(encrypted, len));\n");
    code.push_str("    free(encrypted);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // ChaCha20-Poly1305 Decryption
    code.push_str("// crypto.ChaCha20Poly1305Decrypt - ChaCha20-Poly1305 authenticated decryption\n");
    code.push_str("char* crypto_ChaCha20Poly1305Decrypt(const char* encrypted, const char* key, const char* nonce, const char* aad) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    if (key_len != 32) { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    // Extract nonce (12 bytes), ciphertext, and tag (16 bytes)\n");
    code.push_str("    int enc_len = strlen(encrypted);\n");
    code.push_str("    if (enc_len < 28) { EVP_CIPHER_CTX_free(ctx); return result; }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char nonce_bytes[12];\n");
    code.push_str("    if (nonce && strlen(nonce) >= 12) {\n");
    code.push_str("        memcpy(nonce_bytes, nonce, 12);\n");
    code.push_str("    } else {\n");
    code.push_str("        memcpy(nonce_bytes, encrypted, 12);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char tag[16];\n");
    code.push_str("    memcpy(tag, encrypted + enc_len - 16, 16);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* ciphertext = (unsigned char*)(encrypted + 12);\n");
    code.push_str("    int ciphertext_len = enc_len - 28;\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(ciphertext_len + 16);\n");
    code.push_str("    int outlen, finallen;\n");
    code.push_str("    \n");
    code.push_str("    EVP_DecryptInit_ex(ctx, EVP_chacha20_poly1305(), NULL, (unsigned char*)key, nonce_bytes);\n");
    code.push_str("    \n");
    code.push_str("    // Add AAD if provided\n");
    code.push_str("    if (aad && strlen(aad) > 0) {\n");
    code.push_str("        int aad_len = strlen(aad);\n");
    code.push_str("        EVP_DecryptUpdate(ctx, NULL, &outlen, (unsigned char*)aad, aad_len);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_DecryptUpdate(ctx, out, &outlen, ciphertext, ciphertext_len);\n");
    code.push_str("    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, 16, tag);\n");
    code.push_str("    \n");
    code.push_str("    int ret = EVP_DecryptFinal_ex(ctx, out + outlen, &finallen);\n");
    code.push_str("    if (ret <= 0) {\n");
    code.push_str("        // Authentication failed\n");
    code.push_str("        free(out);\n");
    code.push_str("        EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    out[outlen + finallen] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)out);\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_CIPHER_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - XOR cipher (NOT SECURE)\n");
    code.push_str("    int len = strlen(encrypted);\n");
    code.push_str("    unsigned char* decrypted = (unsigned char*)malloc(len);\n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    for (int i = 0; i < len; i++) {\n");
    code.push_str("        decrypted[i] = encrypted[i] ^ key[i % key_len];\n");
    code.push_str("    }\n");
    code.push_str("    decrypted[len] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)decrypted);\n");
    code.push_str("    free(decrypted);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // PBKDF2 - Password-Based Key Derivation Function
    code.push_str("// crypto.PBKDF2 - Password-Based Key Derivation Function 2\n");
    code.push_str("char* crypto_PBKDF2(const char* password, const char* salt, int iterations, int keyLength, const char* hashAlgo) {\n");
    code.push_str("    static char result[129];  // Max 64 bytes = 128 hex chars + null\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (keyLength < 1 || keyLength > 64) keyLength = 32;  // Default 32 bytes\n");
    code.push_str("    if (iterations < 1) iterations = 10000;  // Default 10000 iterations\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    const EVP_MD* md = NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Determine hash algorithm\n");
    code.push_str("    if (strcmp(hashAlgo, \"sha1\") == 0 || strcmp(hashAlgo, \"SHA1\") == 0) {\n");
    code.push_str("        md = EVP_sha1();\n");
    code.push_str("    } else if (strcmp(hashAlgo, \"sha256\") == 0 || strcmp(hashAlgo, \"SHA256\") == 0) {\n");
    code.push_str("        md = EVP_sha256();\n");
    code.push_str("    } else if (strcmp(hashAlgo, \"sha512\") == 0 || strcmp(hashAlgo, \"SHA512\") == 0) {\n");
    code.push_str("        md = EVP_sha512();\n");
    code.push_str("    } else {\n");
    code.push_str("        md = EVP_sha256();  // Default to SHA256\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* key = (unsigned char*)malloc(keyLength);\n");
    code.push_str("    \n");
    code.push_str("    int ret = PKCS5_PBKDF2_HMAC(password, strlen(password), (unsigned char*)salt, strlen(salt), iterations, md, keyLength, key);\n");
    code.push_str("    \n");
    code.push_str("    if (ret == 1) {\n");
    code.push_str("        bytes_to_hex(key, keyLength, result);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    free(key);\n");
    code.push_str("#else\n");
    code.push_str("    // Placeholder - simple key derivation (NOT SECURE)\n");
    code.push_str("    // In production, always use OpenSSL PBKDF2\n");
    code.push_str("    char combined[512];\n");
    code.push_str("    snprintf(combined, sizeof(combined), \"%s%s\", password, salt);\n");
    code.push_str("    \n");
    code.push_str("    // Simple repeated hashing (NOT PBKDF2, just for testing)\n");
    code.push_str("    char* temp = (char*)malloc(strlen(combined) + 1);\n");
    code.push_str("    strcpy(temp, combined);\n");
    code.push_str("    for (int i = 0; i < iterations && i < 100; i++) {  // Limit iterations for testing\n");
    code.push_str("        char* hash = hash_SHA256(temp);\n");
    code.push_str("        strcpy(temp, hash);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Take first keyLength bytes\n");
    code.push_str("    strncpy(result, temp, keyLength * 2);\n");
    code.push_str("    result[keyLength * 2] = '\\0';\n");
    code.push_str("    free(temp);\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // RSA Key Generation
    code.push_str("// crypto.RSAGenerateKeyPair - Generate RSA key pair\n");
    code.push_str("char* crypto_RSAGenerateKeyPair(int bits) {\n");
    code.push_str("    static char result[8192];  // Large enough for key pair\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (bits < 512) bits = 2048;  // Default to 2048 bits\n");
    code.push_str("    if (bits > 4096) bits = 4096;  // Max 4096 bits\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, NULL);\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_keygen_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, bits) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = NULL;\n");
    code.push_str("    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Export keys to PEM format\n");
    code.push_str("    BIO* bio_private = BIO_new(BIO_s_mem());\n");
    code.push_str("    BIO* bio_public = BIO_new(BIO_s_mem());\n");
    code.push_str("    \n");
    code.push_str("    PEM_write_bio_PrivateKey(bio_private, pkey, NULL, NULL, 0, NULL, NULL);\n");
    code.push_str("    PEM_write_bio_PUBKEY(bio_public, pkey);\n");
    code.push_str("    \n");
    code.push_str("    BUF_MEM* private_mem;\n");
    code.push_str("    BUF_MEM* public_mem;\n");
    code.push_str("    BIO_get_mem_ptr(bio_private, &private_mem);\n");
    code.push_str("    BIO_get_mem_ptr(bio_public, &public_mem);\n");
    code.push_str("    \n");
    code.push_str("    // Format: \"PRIVATE_KEY|PUBLIC_KEY\"\n");
    code.push_str("    int total_len = private_mem->length + public_mem->length + 2;\n");
    code.push_str("    if (total_len < sizeof(result)) {\n");
    code.push_str("        memcpy(result, private_mem->data, private_mem->length);\n");
    code.push_str("        result[private_mem->length] = '|';\n");
    code.push_str("        memcpy(result + private_mem->length + 1, public_mem->data, public_mem->length);\n");
    code.push_str("        result[total_len - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    BIO_free(bio_private);\n");
    code.push_str("    BIO_free(bio_public);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"RSA requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // RSA Encryption
    code.push_str("// crypto.RSAEncrypt - RSA encryption with public key\n");
    code.push_str("char* crypto_RSAEncrypt(const char* data, const char* publicKeyPEM) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(publicKeyPEM, -1);\n");
    code.push_str("    if (!bio) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new(pkey, NULL);\n");
    code.push_str("    if (!ctx) { EVP_PKEY_free(pkey); return result; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_encrypt_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_OAEP_PADDING) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    size_t outlen;\n");
    code.push_str("    int data_len = strlen(data);\n");
    code.push_str("    \n");
    code.push_str("    // Determine output buffer size\n");
    code.push_str("    if (EVP_PKEY_encrypt(ctx, NULL, &outlen, (unsigned char*)data, data_len) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(outlen);\n");
    code.push_str("    if (EVP_PKEY_encrypt(ctx, out, &outlen, (unsigned char*)data, data_len) <= 0) {\n");
    code.push_str("        free(out);\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    strcpy(result, base64_encode_simple(out, outlen));\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"RSA requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // RSA Decryption
    code.push_str("// crypto.RSADecrypt - RSA decryption with private key\n");
    code.push_str("char* crypto_RSADecrypt(const char* encrypted, const char* privateKeyPEM) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(privateKeyPEM, -1);\n");
    code.push_str("    if (!bio) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new(pkey, NULL);\n");
    code.push_str("    if (!ctx) { EVP_PKEY_free(pkey); return result; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_decrypt_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_OAEP_PADDING) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Base64 decode encrypted data (simplified - use proper base64 in production)\n");
    code.push_str("    int enc_len = strlen(encrypted);\n");
    code.push_str("    unsigned char* ciphertext = (unsigned char*)encrypted;  // Simplified\n");
    code.push_str("    \n");
    code.push_str("    size_t outlen;\n");
    code.push_str("    if (EVP_PKEY_decrypt(ctx, NULL, &outlen, ciphertext, enc_len) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(outlen);\n");
    code.push_str("    if (EVP_PKEY_decrypt(ctx, out, &outlen, ciphertext, enc_len) <= 0) {\n");
    code.push_str("        free(out);\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    out[outlen] = '\\0';\n");
    code.push_str("    strcpy(result, (char*)out);\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"RSA requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // RSA Sign
    code.push_str("// crypto.RSASign - Create RSA digital signature\n");
    code.push_str("char* crypto_RSASign(const char* data, const char* privateKeyPEM) {\n");
    code.push_str("    static char result[1024];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(privateKeyPEM, -1);\n");
    code.push_str("    if (!bio) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return result; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignInit(mdctx, NULL, EVP_sha256(), NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    size_t siglen;\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, NULL, &siglen) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(siglen);\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, sig, &siglen) <= 0) {\n");
    code.push_str("        free(sig);\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    bytes_to_hex(sig, siglen, result);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"RSA requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // RSA Verify
    code.push_str("// crypto.RSAVerify - Verify RSA digital signature\n");
    code.push_str("int crypto_RSAVerify(const char* data, const char* signature, const char* publicKeyPEM) {\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(publicKeyPEM, -1);\n");
    code.push_str("    if (!bio) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return 0; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyInit(mdctx, NULL, EVP_sha256(), NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Convert hex signature to bytes\n");
    code.push_str("    int sig_len = strlen(signature) / 2;\n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(sig_len);\n");
    code.push_str("    hex_to_bytes(signature, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    int ret = EVP_DigestVerifyFinal(mdctx, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    \n");
    code.push_str("    return (ret == 1) ? 1 : 0;\n");
    code.push_str("#else\n");
    code.push_str("    return 0;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // ECDSA Key Generation
    code.push_str("// crypto.ECCGenerateKeyPair - Generate ECC key pair\n");
    code.push_str("char* crypto_ECCGenerateKeyPair(const char* curve) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    int nid;\n");
    code.push_str("    \n");
    code.push_str("    // Determine curve\n");
    code.push_str("    if (strcmp(curve, \"P-256\") == 0 || strcmp(curve, \"secp256r1\") == 0) {\n");
    code.push_str("        nid = NID_X9_62_prime256v1;\n");
    code.push_str("    } else if (strcmp(curve, \"P-384\") == 0 || strcmp(curve, \"secp384r1\") == 0) {\n");
    code.push_str("        nid = NID_secp384r1;\n");
    code.push_str("    } else if (strcmp(curve, \"P-521\") == 0 || strcmp(curve, \"secp521r1\") == 0) {\n");
    code.push_str("        nid = NID_secp521r1;\n");
    code.push_str("    } else {\n");
    code.push_str("        nid = NID_X9_62_prime256v1;  // Default to P-256\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_EC, NULL);\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_keygen_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_CTX_set_ec_paramgen_curve_nid(ctx, nid) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = NULL;\n");
    code.push_str("    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Export keys to PEM format\n");
    code.push_str("    BIO* bio_private = BIO_new(BIO_s_mem());\n");
    code.push_str("    BIO* bio_public = BIO_new(BIO_s_mem());\n");
    code.push_str("    \n");
    code.push_str("    PEM_write_bio_PrivateKey(bio_private, pkey, NULL, NULL, 0, NULL, NULL);\n");
    code.push_str("    PEM_write_bio_PUBKEY(bio_public, pkey);\n");
    code.push_str("    \n");
    code.push_str("    BUF_MEM* private_mem;\n");
    code.push_str("    BUF_MEM* public_mem;\n");
    code.push_str("    BIO_get_mem_ptr(bio_private, &private_mem);\n");
    code.push_str("    BIO_get_mem_ptr(bio_public, &public_mem);\n");
    code.push_str("    \n");
    code.push_str("    int total_len = private_mem->length + public_mem->length + 2;\n");
    code.push_str("    if (total_len < sizeof(result)) {\n");
    code.push_str("        memcpy(result, private_mem->data, private_mem->length);\n");
    code.push_str("        result[private_mem->length] = '|';\n");
    code.push_str("        memcpy(result + private_mem->length + 1, public_mem->data, public_mem->length);\n");
    code.push_str("        result[total_len - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    BIO_free(bio_private);\n");
    code.push_str("    BIO_free(bio_public);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"ECC requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // ECDSA Sign
    code.push_str("// crypto.ECDSASign - Create ECDSA digital signature\n");
    code.push_str("char* crypto_ECDSASign(const char* data, const char* privateKeyPEM) {\n");
    code.push_str("    static char result[512];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(privateKeyPEM, -1);\n");
    code.push_str("    if (!bio) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return result; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignInit(mdctx, NULL, EVP_sha256(), NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    size_t siglen;\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, NULL, &siglen) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(siglen);\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, sig, &siglen) <= 0) {\n");
    code.push_str("        free(sig);\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    bytes_to_hex(sig, siglen, result);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"ECDSA requires OpenSSL\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // ECDSA Verify
    code.push_str("// crypto.ECDSAVerify - Verify ECDSA digital signature\n");
    code.push_str("int crypto_ECDSAVerify(const char* data, const char* signature, const char* publicKeyPEM) {\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(publicKeyPEM, -1);\n");
    code.push_str("    if (!bio) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return 0; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyInit(mdctx, NULL, EVP_sha256(), NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Convert hex signature to bytes\n");
    code.push_str("    int sig_len = strlen(signature) / 2;\n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(sig_len);\n");
    code.push_str("    hex_to_bytes(signature, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    int ret = EVP_DigestVerifyFinal(mdctx, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    \n");
    code.push_str("    return (ret == 1) ? 1 : 0;\n");
    code.push_str("#else\n");
    code.push_str("    return 0;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // Argon2 (Note: Argon2 requires libargon2, but we'll provide a placeholder that uses PBKDF2 as fallback)
    code.push_str("// crypto.Argon2Hash - Argon2 password hashing (memory-hard)\n");
    code.push_str("char* crypto_Argon2Hash(const char* password, const char* salt, int timeCost, int memoryCost, int parallelism) {\n");
    code.push_str("    static char result[129];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (timeCost < 1) timeCost = 2;  // Default time cost\n");
    code.push_str("    if (memoryCost < 1) memoryCost = 65536;  // Default 64 MB\n");
    code.push_str("    if (parallelism < 1) parallelism = 4;  // Default parallelism\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    // OpenSSL 1.1.1+ has Argon2 support via EVP\n");
    code.push_str("    // For older versions, fall back to PBKDF2 with high iterations\n");
    code.push_str("    \n");
    code.push_str("    // Try Argon2id (most secure variant)\n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_SCRYPT, NULL);\n");
    code.push_str("    if (ctx) {\n");
    code.push_str("        // Use scrypt as approximation (similar memory-hard KDF)\n");
    code.push_str("        unsigned char* out = (unsigned char*)malloc(32);\n");
    code.push_str("        \n");
    code.push_str("        if (EVP_PKEY_derive_init(ctx) > 0) {\n");
    code.push_str("            EVP_PKEY_CTX_set1_pbe_pass(ctx, password, strlen(password));\n");
    code.push_str("            EVP_PKEY_CTX_set1_scrypt_salt(ctx, (unsigned char*)salt, strlen(salt));\n");
    code.push_str("            EVP_PKEY_CTX_set_scrypt_N(ctx, memoryCost);\n");
    code.push_str("            EVP_PKEY_CTX_set_scrypt_r(ctx, 8);\n");
    code.push_str("            EVP_PKEY_CTX_set_scrypt_p(ctx, parallelism);\n");
    code.push_str("            \n");
    code.push_str("            size_t outlen = 32;\n");
    code.push_str("            if (EVP_PKEY_derive(ctx, out, &outlen) > 0) {\n");
    code.push_str("                bytes_to_hex(out, 32, result);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        free(out);\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        if (result[0] != '\\0') return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Fallback to PBKDF2 with high iterations\n");
    code.push_str("    int iterations = timeCost * 10000;\n");
    code.push_str("    strcpy(result, crypto_PBKDF2(password, salt, iterations, 32, \"sha256\"));\n");
    code.push_str("#else\n");
    code.push_str("    // Fallback to PBKDF2\n");
    code.push_str("    int iterations = timeCost * 10000;\n");
    code.push_str("    strcpy(result, crypto_PBKDF2(password, salt, iterations, 32, \"sha256\"));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Argon2 Verify
    code.push_str("// crypto.Argon2Verify - Verify Argon2 password hash\n");
    code.push_str("int crypto_Argon2Verify(const char* password, const char* hash) {\n");
    code.push_str("    \n");
    code.push_str("    // Extract salt and parameters from hash (simplified)\n");
    code.push_str("    // In production, use proper Argon2 hash format: $argon2id$v=19$m=65536,t=2,p=4$salt$hash\n");
    code.push_str("    \n");
    code.push_str("    // For now, use PBKDF2 verification as approximation\n");
    code.push_str("    // Extract salt (first 16 bytes of hash as hex = 32 chars)\n");
    code.push_str("    char salt[33];\n");
    code.push_str("    strncpy(salt, hash, 32);\n");
    code.push_str("    salt[32] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    // Recompute hash and compare\n");
    code.push_str("    char* computed = crypto_Argon2Hash(password, salt, 2, 65536, 4);\n");
    code.push_str("    \n");
    code.push_str("    int match = (strcmp(computed, hash) == 0);\n");
    code.push_str("    return match ? 1 : 0;\n");
    code.push_str("}\n\n");
    
    // Ed25519 Key Generation
    code.push_str("// crypto.Ed25519GenerateKeyPair - Generate Ed25519 key pair\n");
    code.push_str("char* crypto_Ed25519GenerateKeyPair() {\n");
    code.push_str("    static char result[1024];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_ED25519, NULL);\n");
    code.push_str("    if (!ctx) return result;\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_keygen_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = NULL;\n");
    code.push_str("    if (EVP_PKEY_keygen(ctx, &pkey) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Export keys to PEM format\n");
    code.push_str("    BIO* bio_private = BIO_new(BIO_s_mem());\n");
    code.push_str("    BIO* bio_public = BIO_new(BIO_s_mem());\n");
    code.push_str("    \n");
    code.push_str("    PEM_write_bio_PrivateKey(bio_private, pkey, NULL, NULL, 0, NULL, NULL);\n");
    code.push_str("    PEM_write_bio_PUBKEY(bio_public, pkey);\n");
    code.push_str("    \n");
    code.push_str("    BUF_MEM* private_mem;\n");
    code.push_str("    BUF_MEM* public_mem;\n");
    code.push_str("    BIO_get_mem_ptr(bio_private, &private_mem);\n");
    code.push_str("    BIO_get_mem_ptr(bio_public, &public_mem);\n");
    code.push_str("    \n");
    code.push_str("    int total_len = private_mem->length + public_mem->length + 2;\n");
    code.push_str("    if (total_len < sizeof(result)) {\n");
    code.push_str("        memcpy(result, private_mem->data, private_mem->length);\n");
    code.push_str("        result[private_mem->length] = '|';\n");
    code.push_str("        memcpy(result + private_mem->length + 1, public_mem->data, public_mem->length);\n");
    code.push_str("        result[total_len - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    BIO_free(bio_private);\n");
    code.push_str("    BIO_free(bio_public);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"Ed25519 requires OpenSSL 1.1.1+\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Ed25519 Sign
    code.push_str("// crypto.Ed25519Sign - Create Ed25519 digital signature\n");
    code.push_str("char* crypto_Ed25519Sign(const char* data, const char* privateKeyPEM) {\n");
    code.push_str("    static char result[256];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(privateKeyPEM, -1);\n");
    code.push_str("    if (!bio) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PrivateKey(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return result;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return result; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignInit(mdctx, NULL, NULL, NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestSignUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    size_t siglen;\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, NULL, &siglen) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(siglen);\n");
    code.push_str("    if (EVP_DigestSignFinal(mdctx, sig, &siglen) <= 0) {\n");
    code.push_str("        free(sig);\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    bytes_to_hex(sig, siglen, result);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("#else\n");
    code.push_str("    strcpy(result, \"Ed25519 requires OpenSSL 1.1.1+\");\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Ed25519 Verify
    code.push_str("// crypto.Ed25519Verify - Verify Ed25519 digital signature\n");
    code.push_str("int crypto_Ed25519Verify(const char* data, const char* signature, const char* publicKeyPEM) {\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    BIO* bio = BIO_new_mem_buf(publicKeyPEM, -1);\n");
    code.push_str("    if (!bio) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);\n");
    code.push_str("    BIO_free(bio);\n");
    code.push_str("    if (!pkey) return 0;\n");
    code.push_str("    \n");
    code.push_str("    EVP_MD_CTX* mdctx = EVP_MD_CTX_new();\n");
    code.push_str("    if (!mdctx) { EVP_PKEY_free(pkey); return 0; }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyInit(mdctx, NULL, NULL, NULL, pkey) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_DigestVerifyUpdate(mdctx, data, strlen(data)) <= 0) {\n");
    code.push_str("        EVP_MD_CTX_free(mdctx);\n");
    code.push_str("        EVP_PKEY_free(pkey);\n");
    code.push_str("        return 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Convert hex signature to bytes\n");
    code.push_str("    int sig_len = strlen(signature) / 2;\n");
    code.push_str("    unsigned char* sig = (unsigned char*)malloc(sig_len);\n");
    code.push_str("    hex_to_bytes(signature, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    int ret = EVP_DigestVerifyFinal(mdctx, sig, sig_len);\n");
    code.push_str("    \n");
    code.push_str("    free(sig);\n");
    code.push_str("    EVP_MD_CTX_free(mdctx);\n");
    code.push_str("    EVP_PKEY_free(pkey);\n");
    code.push_str("    \n");
    code.push_str("    return (ret == 1) ? 1 : 0;\n");
    code.push_str("#else\n");
    code.push_str("    return 0;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // bcrypt Hash
    code.push_str("// crypto.BcryptHash - bcrypt password hashing\n");
    code.push_str("char* crypto_BcryptHash(const char* password, int cost) {\n");
    code.push_str("    static char result[61];  // bcrypt hash is 60 chars\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (cost < 4) cost = 10;  // Default cost factor\n");
    code.push_str("    if (cost > 31) cost = 31;  // Max cost factor\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    // OpenSSL 1.1.0+ has bcrypt support via EVP\n");
    code.push_str("    // Generate random salt\n");
    code.push_str("    unsigned char salt[16];\n");
    code.push_str("    RAND_bytes(salt, 16);\n");
    code.push_str("    \n");
    code.push_str("    // Use EVP_PBE_scrypt as approximation (bcrypt not directly available in all OpenSSL versions)\n");
    code.push_str("    // For true bcrypt, would need libbcrypt or OpenSSL with bcrypt support\n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(24);  // bcrypt output size\n");
    code.push_str("    \n");
    code.push_str("    // Use PBKDF2 with Blowfish-like parameters as approximation\n");
    code.push_str("    // Note: True bcrypt requires libbcrypt library\n");
    code.push_str("    int iterations = 1 << cost;  // 2^cost iterations\n");
    code.push_str("    \n");
    code.push_str("    // Format as bcrypt-like hash: $2a$cost$salt+hash\n");
    code.push_str("    char salt_b64[23];\n");
    code.push_str("    // Simplified bcrypt format (for compatibility, use proper bcrypt library in production)\n");
    code.push_str("    snprintf(result, sizeof(result), \"$2a$%02d$\", cost);\n");
    code.push_str("    \n");
    code.push_str("    // Use PBKDF2 as approximation\n");
    code.push_str("    char* pbkdf2_hash = crypto_PBKDF2(password, (char*)salt, iterations, 24, \"sha256\");\n");
    code.push_str("    \n");
    code.push_str("    // Encode salt and hash (simplified)\n");
    code.push_str("    strcat(result, base64_encode_simple(salt, 16));\n");
    code.push_str("    strcat(result, base64_encode_simple((unsigned char*)pbkdf2_hash, 24));\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("#else\n");
    code.push_str("    // Fallback: Use PBKDF2 with bcrypt-like cost\n");
    code.push_str("    unsigned char salt[16];\n");
    code.push_str("    for (int i = 0; i < 16; i++) salt[i] = (unsigned char)(rand() % 256);\n");
    code.push_str("    int iterations = 1 << cost;\n");
    code.push_str("    strcpy(result, crypto_PBKDF2(password, (char*)salt, iterations, 24, \"sha256\"));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // bcrypt Verify
    code.push_str("// crypto.BcryptVerify - Verify bcrypt password hash\n");
    code.push_str("int crypto_BcryptVerify(const char* password, const char* hash) {\n");
    code.push_str("    \n");
    code.push_str("    // Parse bcrypt hash format: $2a$cost$salt+hash\n");
    code.push_str("    if (strncmp(hash, \"$2a$\", 5) != 0 && strncmp(hash, \"$2b$\", 5) != 0 && strncmp(hash, \"$2y$\", 5) != 0) {\n");
    code.push_str("        // Not a bcrypt hash, try direct comparison\n");
    code.push_str("        char* computed = crypto_BcryptHash(password, 10);\n");
    code.push_str("        int match = (strcmp(computed, hash) == 0);\n");
    code.push_str("        return match ? 1 : 0;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Extract cost from hash\n");
    code.push_str("    int cost = 10;\n");
    code.push_str("    if (strlen(hash) > 7) {\n");
    code.push_str("        cost = (hash[4] - '0') * 10 + (hash[5] - '0');\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Recompute hash with same cost\n");
    code.push_str("    char* computed = crypto_BcryptHash(password, cost);\n");
    code.push_str("    \n");
    code.push_str("    // Compare (simplified - proper bcrypt would parse salt and hash separately)\n");
    code.push_str("    int match = (strcmp(computed, hash) == 0);\n");
    code.push_str("    return match ? 1 : 0;\n");
    code.push_str("}\n\n");
    
    // scrypt Key Derivation
    code.push_str("// crypto.Scrypt - scrypt memory-hard key derivation\n");
    code.push_str("char* crypto_Scrypt(const char* password, const char* salt, int N, int r, int p, int keyLength) {\n");
    code.push_str("    static char result[129];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    if (keyLength < 1 || keyLength > 64) keyLength = 32;  // Default 32 bytes\n");
    code.push_str("    if (N < 1) N = 16384;  // Default N (CPU/memory cost)\n");
    code.push_str("    if (r < 1) r = 8;  // Default r (block size)\n");
    code.push_str("    if (p < 1) p = 1;  // Default p (parallelism)\n");
    code.push_str("    \n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    // OpenSSL 1.1.0+ has scrypt support via EVP_PKEY_SCRYPT\n");
    code.push_str("    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_SCRYPT, NULL);\n");
    code.push_str("    if (!ctx) {\n");
    code.push_str("        // Fallback to PBKDF2\n");
    code.push_str("        int iterations = N * r * p;\n");
    code.push_str("        strcpy(result, crypto_PBKDF2(password, salt, iterations, keyLength, \"sha256\"));\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_derive_init(ctx) <= 0) {\n");
    code.push_str("        EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("        int iterations = N * r * p;\n");
    code.push_str("        strcpy(result, crypto_PBKDF2(password, salt, iterations, keyLength, \"sha256\"));\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    EVP_PKEY_CTX_set1_pbe_pass(ctx, password, strlen(password));\n");
    code.push_str("    EVP_PKEY_CTX_set1_scrypt_salt(ctx, (unsigned char*)salt, strlen(salt));\n");
    code.push_str("    EVP_PKEY_CTX_set_scrypt_N(ctx, N);\n");
    code.push_str("    EVP_PKEY_CTX_set_scrypt_r(ctx, r);\n");
    code.push_str("    EVP_PKEY_CTX_set_scrypt_p(ctx, p);\n");
    code.push_str("    \n");
    code.push_str("    unsigned char* out = (unsigned char*)malloc(keyLength);\n");
    code.push_str("    size_t outlen = keyLength;\n");
    code.push_str("    \n");
    code.push_str("    if (EVP_PKEY_derive(ctx, out, &outlen) > 0) {\n");
    code.push_str("        bytes_to_hex(out, keyLength, result);\n");
    code.push_str("    } else {\n");
    code.push_str("        // Fallback to PBKDF2\n");
    code.push_str("        int iterations = N * r * p;\n");
    code.push_str("        strcpy(result, crypto_PBKDF2(password, salt, iterations, keyLength, \"sha256\"));\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    free(out);\n");
    code.push_str("    EVP_PKEY_CTX_free(ctx);\n");
    code.push_str("#else\n");
    code.push_str("    // Fallback to PBKDF2 with scrypt-like iterations\n");
    code.push_str("    int iterations = N * r * p;\n");
    code.push_str("    strcpy(result, crypto_PBKDF2(password, salt, iterations, keyLength, \"sha256\"));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    code
}
