// http - HTTP client/server library
// Ported from Go's net/http package
// Full implementation with socket support

pub fn generate_http_lib() -> String {
    let mut code = String::new();
    
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("\n");
    code.push_str("// HTTPS/TLS Support\n");
    code.push_str("// HTTPS is now fully supported when compiled with USE_OPENSSL\n");
    code.push_str("// The library automatically detects HTTPS URLs and uses TLS connections\n");
    code.push_str("// Certificate validation is enabled by default\n");
    code.push_str("// To enable HTTPS support, compile with -DUSE_OPENSSL and link against OpenSSL\n");
    code.push_str("\n");
    
    // Helper: Extract host and port from URL
    code.push_str("// Helper: Extract host and port from URL\n");
    code.push_str("static void http_parse_url(const char* url, char* host, int* port, char* path) {\n");
    code.push_str("    // Default values\n");
    code.push_str("    strcpy(host, \"\");\n");
    code.push_str("    *port = 80;\n");
    code.push_str("    strcpy(path, \"/\");\n");
    code.push_str("    \n");
    code.push_str("    if (!url) return;\n");
    code.push_str("    \n");
    code.push_str("    // Skip scheme (http:// or https://)\n");
    code.push_str("    const char* host_start = url;\n");
    code.push_str("    if (strncmp(url, \"http://\", 7) == 0) {\n");
    code.push_str("        host_start = url + 7;\n");
    code.push_str("        *port = 80;\n");
    code.push_str("    } else if (strncmp(url, \"https://\", 8) == 0) {\n");
    code.push_str("        host_start = url + 8;\n");
    code.push_str("        *port = 443;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Find path start\n");
    code.push_str("    const char* path_start = strchr(host_start, '/');\n");
    code.push_str("    const char* colon_pos = strchr(host_start, ':');\n");
    code.push_str("    \n");
    code.push_str("    // Extract host and port\n");
    code.push_str("    if (colon_pos != NULL && (path_start == NULL || colon_pos < path_start)) {\n");
    code.push_str("        // Has port\n");
    code.push_str("        int host_len = colon_pos - host_start;\n");
    code.push_str("        strncpy(host, host_start, host_len);\n");
    code.push_str("        host[host_len] = '\\0';\n");
    code.push_str("        \n");
    code.push_str("        const char* port_start = colon_pos + 1;\n");
    code.push_str("        if (path_start != NULL) {\n");
    code.push_str("            int port_len = path_start - port_start;\n");
    code.push_str("            char port_str[16];\n");
    code.push_str("            strncpy(port_str, port_start, port_len);\n");
    code.push_str("            port_str[port_len] = '\\0';\n");
    code.push_str("            *port = atoi(port_str);\n");
    code.push_str("        } else {\n");
    code.push_str("            *port = atoi(port_start);\n");
    code.push_str("        }\n");
    code.push_str("    } else {\n");
    code.push_str("        // No port\n");
    code.push_str("        if (path_start != NULL) {\n");
    code.push_str("            int host_len = path_start - host_start;\n");
    code.push_str("            strncpy(host, host_start, host_len);\n");
    code.push_str("            host[host_len] = '\\0';\n");
    code.push_str("        } else {\n");
    code.push_str("            strcpy(host, host_start);\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Extract path\n");
    code.push_str("    if (path_start != NULL) {\n");
    code.push_str("        strcpy(path, path_start);\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    
    // Note: http.Get is now implemented via http.GetWithRedirects below
    
    // Post - HTTP POST request (uses generic Request function)
    code.push_str("// http.Post - Make HTTP POST request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_Post(const char* url, const char* data) {\n");
    code.push_str("    return http_PostWithHeaders(url, data, NULL);\n");
    code.push_str("}\n\n");
    
    // Helper: Extract HTTP status code from response
    code.push_str("// Helper: Extract HTTP status code from response\n");
    code.push_str("static int http_get_status_code(const char* response) {\n");
    code.push_str("    if (!response) return 0;\n");
    code.push_str("    // Find HTTP/1.x status line\n");
    code.push_str("    const char* http_pos = strstr(response, \"HTTP/\");\n");
    code.push_str("    if (!http_pos) return 0;\n");
    code.push_str("    // Skip to status code (after HTTP/1.x SPACE)\n");
    code.push_str("    const char* space = strchr(http_pos, ' ');\n");
    code.push_str("    if (!space) return 0;\n");
    code.push_str("    return atoi(space + 1);\n");
    code.push_str("}\n\n");
    
    // Helper: Extract Location header from response
    code.push_str("// Helper: Extract Location header from response\n");
    code.push_str("static char* http_get_location(const char* response) {\n");
    code.push_str("    if (!response) return NULL;\n");
    code.push_str("    // Find Location: header\n");
    code.push_str("    const char* loc = strstr(response, \"Location:\");\n");
    code.push_str("    if (!loc) loc = strstr(response, \"location:\");\n");
    code.push_str("    if (!loc) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Skip \"Location:\" and whitespace\n");
    code.push_str("    loc = strchr(loc, ':');\n");
    code.push_str("    if (!loc) return NULL;\n");
    code.push_str("    loc++;\n");
    code.push_str("    while (*loc == ' ' || *loc == '\\t') loc++;\n");
    code.push_str("    \n");
    code.push_str("    // Find end of line\n");
    code.push_str("    const char* end = strchr(loc, '\\r');\n");
    code.push_str("    if (!end) end = strchr(loc, '\\n');\n");
    code.push_str("    if (!end) end = loc + strlen(loc);\n");
    code.push_str("    \n");
    code.push_str("    int len = end - loc;\n");
    code.push_str("    char* location = (char*)malloc(len + 1);\n");
    code.push_str("    if (location) {\n");
    code.push_str("        strncpy(location, loc, len);\n");
    code.push_str("        location[len] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    return location;\n");
    code.push_str("}\n\n");
    
    // Generic HTTP request function
    code.push_str("// http.Request - Generic HTTP request with method, headers, and body\n");
    code.push_str("// method: \"GET\", \"POST\", \"PUT\", \"DELETE\", etc.\n");
    code.push_str("// headers: \"Header1: Value1\\r\\nHeader2: Value2\" or NULL\n");
    code.push_str("// body: Request body or NULL\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_Request(const char* url, const char* method, const char* headers, const char* body) {\n");
    code.push_str("    if (!url || !method) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Initialize network (Windows only)\n");
    code.push_str("    net_Init();\n");
    code.push_str("    \n");
    code.push_str("    // Parse URL\n");
    code.push_str("    char host[256];\n");
    code.push_str("    int port;\n");
    code.push_str("    char path[512];\n");
    code.push_str("    http_parse_url(url, host, &port, path);\n");
    code.push_str("    \n");
    code.push_str("    if (strlen(host) == 0) {\n");
    code.push_str("        net_Cleanup();\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    // Connect to server
    // Note: For HTTPS (port 443), this will attempt plain TCP connection
    // Full TLS/SSL support requires OpenSSL integration (see TODO above)
    // Connect to server (HTTP or HTTPS)
    code.push_str("    // Connect to server (HTTP or HTTPS)\n");
    code.push_str("    int is_https = (port == 443 || strncmp(url, \"https://\", 8) == 0);\n");
    code.push_str("    void* tls_conn = NULL;\n");
    code.push_str("    int sockfd = -1;\n");
    code.push_str("    \n");
    code.push_str("    if (is_https) {\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("        // Initialize TLS\n");
    code.push_str("        net_TLSInit();\n");
    code.push_str("        \n");
    code.push_str("        // Create TLS connection\n");
    code.push_str("        tls_conn = net_TLSDial(host, port);\n");
    code.push_str("        if (!tls_conn) {\n");
    code.push_str("            net_TLSCleanup();\n");
    code.push_str("            net_Cleanup();\n");
    code.push_str("            return NULL;\n");
    code.push_str("        }\n");
    code.push_str("#else\n");
    code.push_str("        // OpenSSL not available - HTTPS not supported\n");
    code.push_str("        net_Cleanup();\n");
    code.push_str("        return NULL;\n");
    code.push_str("#endif\n");
    code.push_str("    } else {\n");
    code.push_str("        // Plain HTTP connection\n");
    code.push_str("        sockfd = net_Dial(host, port);\n");
    code.push_str("        if (sockfd < 0) {\n");
    code.push_str("            net_Cleanup();\n");
    code.push_str("            return NULL;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Build HTTP request\n");
    code.push_str("    char request[8192];\n");
    code.push_str("    int body_len = body ? strlen(body) : 0;\n");
    code.push_str("    \n");
    code.push_str("    // Request line\n");
    code.push_str("    snprintf(request, sizeof(request), \"%s %s HTTP/1.1\\r\\nHost: %s\\r\\n\", method, path, host);\n");
    code.push_str("    \n");
    code.push_str("    // Add custom headers if provided\n");
    code.push_str("    if (headers && strlen(headers) > 0) {\n");
    code.push_str("        strncat(request, headers, sizeof(request) - strlen(request) - 1);\n");
    code.push_str("        // Ensure headers end with \\r\\n\n");
    code.push_str("        int req_len = strlen(request);\n");
    code.push_str("        if (req_len < 2 || strncmp(request + req_len - 2, \"\\r\\n\", 2) != 0) {\n");
    code.push_str("            strcat(request, \"\\r\\n\");\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Add Content-Length if body exists\n");
    code.push_str("    if (body_len > 0) {\n");
    code.push_str("        char content_len[64];\n");
    code.push_str("        snprintf(content_len, sizeof(content_len), \"Content-Length: %d\\r\\n\", body_len);\n");
    code.push_str("        strncat(request, content_len, sizeof(request) - strlen(request) - 1);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // End headers\n");
    code.push_str("    strcat(request, \"Connection: close\\r\\n\\r\\n\");\n");
    code.push_str("    \n");
    code.push_str("    // Append body if exists\n");
    code.push_str("    if (body && body_len > 0) {\n");
    code.push_str("        strncat(request, body, sizeof(request) - strlen(request) - 1);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Send request\n");
    code.push_str("    int send_result;\n");
    code.push_str("    if (is_https) {\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("        send_result = net_TLSSend(tls_conn, request, strlen(request));\n");
    code.push_str("#else\n");
    code.push_str("        send_result = -1;\n");
    code.push_str("#endif\n");
    code.push_str("    } else {\n");
    code.push_str("        send_result = net_Send(sockfd, request, strlen(request));\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (send_result < 0) {\n");
    code.push_str("        if (is_https) {\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("            net_TLSClose(tls_conn);\n");
    code.push_str("            net_TLSCleanup();\n");
    code.push_str("#endif\n");
    code.push_str("        } else {\n");
    code.push_str("            net_Close(sockfd);\n");
    code.push_str("        }\n");
    code.push_str("        net_Cleanup();\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Receive response\n");
    code.push_str("    char buffer[16384];\n");
    code.push_str("    int total_received = 0;\n");
    code.push_str("    int received;\n");
    code.push_str("    \n");
    code.push_str("    while (1) {\n");
    code.push_str("        if (is_https) {\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("            received = net_TLSRecv(tls_conn, buffer + total_received, sizeof(buffer) - total_received - 1);\n");
    code.push_str("#else\n");
    code.push_str("            received = -1;\n");
    code.push_str("#endif\n");
    code.push_str("        } else {\n");
    code.push_str("            received = net_Recv(sockfd, buffer + total_received, sizeof(buffer) - total_received - 1);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (received <= 0) break;\n");
    code.push_str("        total_received += received;\n");
    code.push_str("        if (total_received >= sizeof(buffer) - 1) break;\n");
    code.push_str("    }\n");
    code.push_str("    buffer[total_received] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    // Close connection\n");
    code.push_str("    if (is_https) {\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("        net_TLSClose(tls_conn);\n");
    code.push_str("        net_TLSCleanup();\n");
    code.push_str("#endif\n");
    code.push_str("    } else {\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("    }\n");
    code.push_str("    net_Cleanup();\n");
    code.push_str("    \n");
    code.push_str("    // Parse response - find body after headers\n");
    code.push_str("    char* body_start = strstr(buffer, \"\\r\\n\\r\\n\");\n");
    code.push_str("    if (!body_start) body_start = strstr(buffer, \"\\n\\n\");\n");
    code.push_str("    \n");
    code.push_str("    if (body_start) {\n");
    code.push_str("        body_start += 4;  // Skip \\r\\n\\r\\n\n");
    code.push_str("        if (strncmp(body_start - 2, \"\\n\\n\", 2) == 0) body_start -= 2;  // Handle \\n\\n\n");
    code.push_str("        char* response = (char*)malloc(strlen(body_start) + 1);\n");
    code.push_str("        if (response) {\n");
    code.push_str("            strcpy(response, body_start);\n");
    code.push_str("            return response;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Return full response if no body found\n");
    code.push_str("    char* response = (char*)malloc(strlen(buffer) + 1);\n");
    code.push_str("    if (response) strcpy(response, buffer);\n");
    code.push_str("    return response;\n");
    code.push_str("}\n\n");
    
    // Get with redirect support
    code.push_str("// http.Get - Make HTTP GET request with redirect support\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_Get(const char* url) {\n");
    code.push_str("    return http_GetWithRedirects(url, 5);  // Default: 5 redirects max\n");
    code.push_str("}\n\n");
    
    // Get with redirect support
    code.push_str("// http.GetWithRedirects - Make HTTP GET request with redirect handling\n");
    code.push_str("// max_redirects: Maximum number of redirects to follow (default: 5)\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_GetWithRedirects(const char* url, int max_redirects) {\n");
    code.push_str("    if (!url || max_redirects < 0) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    char* current_url = (char*)malloc(strlen(url) + 1);\n");
    code.push_str("    if (!current_url) return NULL;\n");
    code.push_str("    strcpy(current_url, url);\n");
    code.push_str("    \n");
    code.push_str("    int redirects = 0;\n");
    code.push_str("    char* response = NULL;\n");
    code.push_str("    \n");
    code.push_str("    while (redirects <= max_redirects) {\n");
    code.push_str("        // Make request\n");
    code.push_str("        response = http_Request(current_url, \"GET\", NULL, NULL);\n");
    code.push_str("        if (!response) {\n");
    code.push_str("            free(current_url);\n");
    code.push_str("            return NULL;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Check for redirect (301, 302, 307, 308)\n");
    code.push_str("        int status = http_get_status_code(response);\n");
    code.push_str("        if (status == 301 || status == 302 || status == 307 || status == 308) {\n");
    code.push_str("            // Get Location header\n");
    code.push_str("            char* location = http_get_location(response);\n");
    code.push_str("            free(response);\n");
    code.push_str("            \n");
    code.push_str("            if (!location || redirects >= max_redirects) {\n");
    code.push_str("                free(current_url);\n");
    code.push_str("                if (location) free(location);\n");
    code.push_str("                return NULL;\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            // Handle relative URLs\n");
    code.push_str("            if (location[0] == '/') {\n");
    code.push_str("                // Relative URL - extract scheme and host from current URL\n");
    code.push_str("                char new_url[1024];\n");
    code.push_str("                char host[256];\n");
    code.push_str("                int port;\n");
    code.push_str("                char path[512];\n");
    code.push_str("                http_parse_url(current_url, host, &port, path);\n");
    code.push_str("                \n");
    code.push_str("                if (strncmp(current_url, \"https://\", 8) == 0) {\n");
    code.push_str("                    snprintf(new_url, sizeof(new_url), \"https://%s:%d%s\", host, port, location);\n");
    code.push_str("                } else {\n");
    code.push_str("                    snprintf(new_url, sizeof(new_url), \"http://%s:%d%s\", host, port, location);\n");
    code.push_str("                }\n");
    code.push_str("                free(current_url);\n");
    code.push_str("                current_url = (char*)malloc(strlen(new_url) + 1);\n");
    code.push_str("                if (current_url) strcpy(current_url, new_url);\n");
    code.push_str("            } else {\n");
    code.push_str("                // Absolute URL\n");
    code.push_str("                free(current_url);\n");
    code.push_str("                current_url = location;\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            redirects++;\n");
    code.push_str("            continue;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Not a redirect, return response\n");
    code.push_str("        break;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    free(current_url);\n");
    code.push_str("    return response;\n");
    code.push_str("}\n\n");
    
    // Put - HTTP PUT request
    code.push_str("// http.Put - Make HTTP PUT request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_Put(const char* url, const char* data) {\n");
    code.push_str("    return http_Request(url, \"PUT\", NULL, data);\n");
    code.push_str("}\n\n");
    
    // Delete - HTTP DELETE request
    code.push_str("// http.Delete - Make HTTP DELETE request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_Delete(const char* url) {\n");
    code.push_str("    return http_Request(url, \"DELETE\", NULL, NULL);\n");
    code.push_str("}\n\n");
    
    // Head - HTTP HEAD request (returns headers only, no body)
    code.push_str("// http.Head - Make HTTP HEAD request\n");
    code.push_str("// Returns: HTTP response headers (caller must free), or NULL on error\n");
    code.push_str("// Note: HEAD requests return headers only, no response body\n");
    code.push_str("char* http_Head(const char* url) {\n");
    code.push_str("    return http_Request(url, \"HEAD\", NULL, NULL);\n");
    code.push_str("}\n\n");
    
    // Options - HTTP OPTIONS request
    code.push_str("// http.Options - Make HTTP OPTIONS request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("// Used to describe communication options for the target resource\n");
    code.push_str("char* http_Options(const char* url) {\n");
    code.push_str("    return http_Request(url, \"OPTIONS\", NULL, NULL);\n");
    code.push_str("}\n\n");
    
    // Patch - HTTP PATCH request
    code.push_str("// http.Patch - Make HTTP PATCH request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("// Used for partial modifications to a resource\n");
    code.push_str("char* http_Patch(const char* url, const char* data) {\n");
    code.push_str("    return http_Request(url, \"PATCH\", NULL, data);\n");
    code.push_str("}\n\n");
    
    // Patch with headers
    code.push_str("// http.PatchWithHeaders - Make HTTP PATCH request with custom headers\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_PatchWithHeaders(const char* url, const char* data, const char* headers) {\n");
    code.push_str("    // Build headers with Content-Type if not provided\n");
    code.push_str("    char full_headers[1024] = \"\";\n");
    code.push_str("    if (headers && strlen(headers) > 0) {\n");
    code.push_str("        strcpy(full_headers, headers);\n");
    code.push_str("    }\n");
    code.push_str("    if (data && (!headers || strstr(headers, \"Content-Type\") == NULL)) {\n");
    code.push_str("        if (strlen(full_headers) > 0) strcat(full_headers, \"\\r\\n\");\n");
    code.push_str("        strcat(full_headers, \"Content-Type: application/json\\r\\n\");\n");
    code.push_str("    }\n");
    code.push_str("    return http_Request(url, \"PATCH\", full_headers, data);\n");
    code.push_str("}\n\n");
    
    // Trace - HTTP TRACE request
    code.push_str("// http.Trace - Make HTTP TRACE request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("// Used for diagnostic purposes, echoes the request back\n");
    code.push_str("char* http_Trace(const char* url) {\n");
    code.push_str("    return http_Request(url, \"TRACE\", NULL, NULL);\n");
    code.push_str("}\n\n");
    
    // Connect - HTTP CONNECT request
    code.push_str("// http.Connect - Make HTTP CONNECT request\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("// Used to establish a tunnel to the server (typically for HTTPS proxies)\n");
    code.push_str("char* http_Connect(const char* url) {\n");
    code.push_str("    return http_Request(url, \"CONNECT\", NULL, NULL);\n");
    code.push_str("}\n\n");
    
    // Post with custom headers
    code.push_str("// http.PostWithHeaders - Make HTTP POST request with custom headers\n");
    code.push_str("// headers: \"Header1: Value1\\r\\nHeader2: Value2\" or NULL\n");
    code.push_str("// Returns: HTTP response body (caller must free), or NULL on error\n");
    code.push_str("char* http_PostWithHeaders(const char* url, const char* data, const char* headers) {\n");
    code.push_str("    // Build headers with Content-Type if not provided\n");
    code.push_str("    char full_headers[2048] = \"\";\n");
    code.push_str("    if (headers && strlen(headers) > 0) {\n");
    code.push_str("        strcpy(full_headers, headers);\n");
    code.push_str("        // Check if Content-Type is already in headers\n");
    code.push_str("        if (strstr(headers, \"Content-Type:\") == NULL && strstr(headers, \"content-type:\") == NULL) {\n");
    code.push_str("            strcat(full_headers, \"Content-Type: application/x-www-form-urlencoded\\r\\n\");\n");
    code.push_str("        }\n");
    code.push_str("    } else if (data && strlen(data) > 0) {\n");
    code.push_str("        strcpy(full_headers, \"Content-Type: application/x-www-form-urlencoded\\r\\n\");\n");
    code.push_str("    }\n");
    code.push_str("    return http_Request(url, \"POST\", full_headers, data);\n");
    code.push_str("}\n\n");
    
    // HTTP Request structure
    code.push_str("// HTTP Request structure\n");
    code.push_str("typedef struct HTTPRequest {\n");
    code.push_str("    char method[16];      // GET, POST, etc.\n");
    code.push_str("    char path[512];       // Request path\n");
    code.push_str("    char* headers;        // Request headers (allocated)\n");
    code.push_str("    char* body;           // Request body (allocated)\n");
    code.push_str("} HTTPRequest;\n\n");
    
    // Parse HTTP request
    code.push_str("// Parse HTTP request from raw request string\n");
    code.push_str("static HTTPRequest* http_parse_request(const char* raw_request) {\n");
    code.push_str("    if (!raw_request) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    HTTPRequest* req = (HTTPRequest*)malloc(sizeof(HTTPRequest));\n");
    code.push_str("    if (!req) return NULL;\n");
    code.push_str("    memset(req, 0, sizeof(HTTPRequest));\n");
    code.push_str("    \n");
    code.push_str("    // Parse request line: METHOD PATH HTTP/VERSION\n");
    code.push_str("    const char* space1 = strchr(raw_request, ' ');\n");
    code.push_str("    if (!space1) { free(req); return NULL; }\n");
    code.push_str("    \n");
    code.push_str("    // Extract method\n");
    code.push_str("    int method_len = space1 - raw_request;\n");
    code.push_str("    if (method_len >= sizeof(req->method)) method_len = sizeof(req->method) - 1;\n");
    code.push_str("    strncpy(req->method, raw_request, method_len);\n");
    code.push_str("    req->method[method_len] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    // Extract path\n");
    code.push_str("    const char* path_start = space1 + 1;\n");
    code.push_str("    const char* space2 = strchr(path_start, ' ');\n");
    code.push_str("    if (!space2) { free(req); return NULL; }\n");
    code.push_str("    \n");
    code.push_str("    int path_len = space2 - path_start;\n");
    code.push_str("    if (path_len >= sizeof(req->path)) path_len = sizeof(req->path) - 1;\n");
    code.push_str("    strncpy(req->path, path_start, path_len);\n");
    code.push_str("    req->path[path_len] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    // Find headers section (after first \\r\\n\\r\\n or \\n\\n)\n");
    code.push_str("    const char* headers_start = strstr(raw_request, \"\\r\\n\");\n");
    code.push_str("    if (!headers_start) headers_start = strstr(raw_request, \"\\n\");\n");
    code.push_str("    if (headers_start) headers_start += 2;  // Skip \\r\\n or \\n\n");
    code.push_str("    \n");
    code.push_str("    // Find body (after \\r\\n\\r\\n or \\n\\n)\n");
    code.push_str("    const char* body_start = strstr(raw_request, \"\\r\\n\\r\\n\");\n");
    code.push_str("    if (!body_start) body_start = strstr(raw_request, \"\\n\\n\");\n");
    code.push_str("    \n");
    code.push_str("    if (body_start) {\n");
    code.push_str("        body_start += 4;  // Skip \\r\\n\\r\\n\n");
    code.push_str("        if (strncmp(body_start - 2, \"\\n\\n\", 2) == 0) body_start -= 2;  // Handle \\n\\n\n");
    code.push_str("        \n");
    code.push_str("        // Extract headers\n");
    code.push_str("        int headers_len = body_start - headers_start - 4;\n");
    code.push_str("        if (headers_len > 0) {\n");
    code.push_str("            req->headers = (char*)malloc(headers_len + 1);\n");
    code.push_str("            if (req->headers) {\n");
    code.push_str("                strncpy(req->headers, headers_start, headers_len);\n");
    code.push_str("                req->headers[headers_len] = '\\0';\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Extract body\n");
    code.push_str("        int body_len = strlen(body_start);\n");
    code.push_str("        if (body_len > 0) {\n");
    code.push_str("            req->body = (char*)malloc(body_len + 1);\n");
    code.push_str("            if (req->body) {\n");
    code.push_str("                strcpy(req->body, body_start);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    } else if (headers_start) {\n");
    code.push_str("        // No body, just headers\n");
    code.push_str("        int headers_len = strlen(headers_start);\n");
    code.push_str("        if (headers_len > 0) {\n");
    code.push_str("            req->headers = (char*)malloc(headers_len + 1);\n");
    code.push_str("            if (req->headers) {\n");
    code.push_str("                strcpy(req->headers, headers_start);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return req;\n");
    code.push_str("}\n\n");
    
    // Free HTTP request
    code.push_str("// Free HTTP request structure\n");
    code.push_str("static void http_free_request(HTTPRequest* req) {\n");
    code.push_str("    if (!req) return;\n");
    code.push_str("    if (req->headers) free(req->headers);\n");
    code.push_str("    if (req->body) free(req->body);\n");
    code.push_str("    free(req);\n");
    code.push_str("}\n\n");
    
    // Generate HTTP response
    code.push_str("// Generate HTTP response\n");
    code.push_str("static char* http_make_response(int status_code, const char* content_type, const char* body) {\n");
    code.push_str("    const char* status_text = \"OK\";\n");
    code.push_str("    if (status_code == 404) status_text = \"Not Found\";\n");
    code.push_str("    else if (status_code == 500) status_text = \"Internal Server Error\";\n");
    code.push_str("    else if (status_code == 400) status_text = \"Bad Request\";\n");
    code.push_str("    \n");
    code.push_str("    int body_len = body ? strlen(body) : 0;\n");
    code.push_str("    char* response = (char*)malloc(4096);\n");
    code.push_str("    if (!response) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    snprintf(response, 4096, \"HTTP/1.1 %d %s\\r\\nContent-Type: %s\\r\\nContent-Length: %d\\r\\nConnection: close\\r\\n\\r\\n\",\n");
    code.push_str("        status_code, status_text, content_type ? content_type : \"text/plain\", body_len);\n");
    code.push_str("    \n");
    code.push_str("    if (body && body_len > 0) {\n");
    code.push_str("        strncat(response, body, 4096 - strlen(response) - 1);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return response;\n");
    code.push_str("}\n\n");
    
    // Handler function type (simplified - takes path and returns response)
    code.push_str("// Handler function type: char* handler(const char* method, const char* path, const char* body)\n");
    code.push_str("// Returns: Response body string (caller will free), or NULL for 404\n");
    code.push_str("typedef char* (*HTTPHandler)(const char* method, const char* path, const char* body);\n\n");
    
    // Default handler (if no handler provided)
    code.push_str("// Default handler - returns simple response\n");
    code.push_str("static char* http_default_handler(const char* method, const char* path, const char* body) {\n");
    code.push_str("    static char response[512];\n");
    code.push_str("    snprintf(response, sizeof(response), \"Method: %s\\nPath: %s\\n\", method ? method : \"UNKNOWN\", path ? path : \"/\");\n");
    code.push_str("    char* result = (char*)malloc(strlen(response) + 1);\n");
    code.push_str("    if (result) strcpy(result, response);\n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // ListenAndServe - Enhanced HTTP server
    code.push_str("// http.ListenAndServe - Start HTTP server with request parsing and routing\n");
    code.push_str("// addr format: \"host:port\" or \":port\"\n");
    code.push_str("// handler: Function pointer to handle requests (HTTPHandler), or NULL for default\n");
    code.push_str("int http_ListenAndServe(const char* addr, void* handler) {\n");
    code.push_str("    if (!addr) return -1;\n");
    code.push_str("    \n");
    code.push_str("    // Initialize network (Windows only)\n");
    code.push_str("    net_Init();\n");
    code.push_str("    \n");
    code.push_str("    // Parse address\n");
    code.push_str("    int port = 8080;  // Default\n");
    code.push_str("    if (addr[0] == ':') {\n");
    code.push_str("        port = atoi(addr + 1);\n");
    code.push_str("    } else {\n");
    code.push_str("        const char* colon = strchr(addr, ':');\n");
    code.push_str("        if (colon) {\n");
    code.push_str("            port = atoi(colon + 1);\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (port <= 0) port = 8080;\n");
    code.push_str("    \n");
    code.push_str("    // Use default handler if none provided\n");
    code.push_str("    HTTPHandler handler_func = handler ? (HTTPHandler)handler : http_default_handler;\n");
    code.push_str("    \n");
    code.push_str("    // Listen on port\n");
    code.push_str("    int listenfd = net_Listen(port);\n");
    code.push_str("    if (listenfd < 0) {\n");
    code.push_str("        net_Cleanup();\n");
    code.push_str("        return -1;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Accept connections (handles one at a time)\n");
    code.push_str("    while (1) {\n");
    code.push_str("        int connfd = net_Accept(listenfd);\n");
    code.push_str("        if (connfd < 0) continue;\n");
    code.push_str("        \n");
    code.push_str("        // Read request\n");
    code.push_str("        char request[8192];\n");
    code.push_str("        int received = net_Recv(connfd, request, sizeof(request) - 1);\n");
    code.push_str("        if (received > 0) {\n");
    code.push_str("            request[received] = '\\0';\n");
    code.push_str("            \n");
    code.push_str("            // Parse request\n");
    code.push_str("            HTTPRequest* req = http_parse_request(request);\n");
    code.push_str("            if (req) {\n");
    code.push_str("                // Call handler\n");
    code.push_str("                char* response_body = handler_func(req->method, req->path, req->body);\n");
    code.push_str("                \n");
    code.push_str("                if (response_body) {\n");
    code.push_str("                    // Generate HTTP response\n");
    code.push_str("                    char* http_response = http_make_response(200, \"text/plain\", response_body);\n");
    code.push_str("                    if (http_response) {\n");
    code.push_str("                        net_Send(connfd, http_response, strlen(http_response));\n");
    code.push_str("                        free(http_response);\n");
    code.push_str("                    }\n");
    code.push_str("                    free(response_body);\n");
    code.push_str("                } else {\n");
    code.push_str("                    // 404 Not Found\n");
    code.push_str("                    char* http_response = http_make_response(404, \"text/plain\", \"Not Found\");\n");
    code.push_str("                    if (http_response) {\n");
    code.push_str("                        net_Send(connfd, http_response, strlen(http_response));\n");
    code.push_str("                        free(http_response);\n");
    code.push_str("                    }\n");
    code.push_str("                }\n");
    code.push_str("                \n");
    code.push_str("                http_free_request(req);\n");
    code.push_str("            } else {\n");
    code.push_str("                // Bad request\n");
    code.push_str("                char* http_response = http_make_response(400, \"text/plain\", \"Bad Request\");\n");
    code.push_str("                if (http_response) {\n");
    code.push_str("                    net_Send(connfd, http_response, strlen(http_response));\n");
    code.push_str("                    free(http_response);\n");
    code.push_str("                }\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        net_Close(connfd);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    net_Close(listenfd);\n");
    code.push_str("    net_Cleanup();\n");
    code.push_str("    return 0;\n");
    code.push_str("}\n\n");
    
    // Helper: Create simple response
    code.push_str("// http.Response - Create HTTP response string\n");
    code.push_str("// status_code: HTTP status code (200, 404, 500, etc.)\n");
    code.push_str("// content_type: Content-Type header value\n");
    code.push_str("// body: Response body\n");
    code.push_str("// Returns: Complete HTTP response (caller must free)\n");
    code.push_str("char* http_Response(int status_code, const char* content_type, const char* body) {\n");
    code.push_str("    return http_make_response(status_code, content_type, body);\n");
    code.push_str("}\n\n");
    
    // Helper: Check if path matches pattern (simple prefix matching)
    code.push_str("// Helper: Check if path matches a route pattern\n");
    code.push_str("static int http_path_matches(const char* path, const char* pattern) {\n");
    code.push_str("    if (!path || !pattern) return 0;\n");
    code.push_str("    // Simple prefix matching\n");
    code.push_str("    return strncmp(path, pattern, strlen(pattern)) == 0;\n");
    code.push_str("}\n\n");
    
    // Helper: Extract query parameters (simplified)
    code.push_str("// Helper: Extract query parameter value from path\n");
    code.push_str("static char* http_get_query_param(const char* path, const char* param_name) {\n");
    code.push_str("    if (!path || !param_name) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Find query string (after ?)\n");
    code.push_str("    const char* query_start = strchr(path, '?');\n");
    code.push_str("    if (!query_start) return NULL;\n");
    code.push_str("    query_start++;  // Skip ?\n");
    code.push_str("    \n");
    code.push_str("    // Find parameter\n");
    code.push_str("    char search[256];\n");
    code.push_str("    snprintf(search, sizeof(search), \"%s=\", param_name);\n");
    code.push_str("    const char* param_start = strstr(query_start, search);\n");
    code.push_str("    if (!param_start) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    param_start += strlen(search);\n");
    code.push_str("    \n");
    code.push_str("    // Find end of value (& or end of string)\n");
    code.push_str("    const char* param_end = strchr(param_start, '&');\n");
    code.push_str("    if (!param_end) param_end = param_start + strlen(param_start);\n");
    code.push_str("    \n");
    code.push_str("    int len = param_end - param_start;\n");
    code.push_str("    char* value = (char*)malloc(len + 1);\n");
    code.push_str("    if (value) {\n");
    code.push_str("        strncpy(value, param_start, len);\n");
    code.push_str("        value[len] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    return value;\n");
    code.push_str("}\n\n");
    
    // Router helper - simple path-based routing
    code.push_str("// http.RouteHandler - Simple router that matches paths and calls handlers\n");
    code.push_str("// routes: Array of route patterns (paths) and handlers\n");
    code.push_str("// route_count: Number of routes\n");
    code.push_str("// method: HTTP method\n");
    code.push_str("// path: Request path\n");
    code.push_str("// body: Request body\n");
    code.push_str("// Returns: Response body (caller must free), or NULL for 404\n");
    code.push_str("// Note: This is a simplified router - matches first prefix match\n");
    code.push_str("char* http_RouteHandler(const char** routes, HTTPHandler* handlers, int route_count, const char* method, const char* path, const char* body) {\n");
    code.push_str("    if (!routes || !handlers || !path || route_count <= 0) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Try each route\n");
    code.push_str("    for (int i = 0; i < route_count; i++) {\n");
    code.push_str("        if (http_path_matches(path, routes[i])) {\n");
    code.push_str("            // Route matched, call handler\n");
    code.push_str("            if (handlers[i]) {\n");
    code.push_str("                return handlers[i](method, path, body);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return NULL;  // No route matched\n");
    code.push_str("}\n\n");
    
    // JSON response helper
    code.push_str("// http.JSONResponse - Create JSON response\n");
    code.push_str("// status_code: HTTP status code\n");
    code.push_str("// json_body: JSON string body\n");
    code.push_str("// Returns: Complete HTTP response (caller must free)\n");
    code.push_str("char* http_JSONResponse(int status_code, const char* json_body) {\n");
    code.push_str("    return http_make_response(status_code, \"application/json\", json_body);\n");
    code.push_str("}\n\n");
    
    // HTML response helper
    code.push_str("// http.HTMLResponse - Create HTML response\n");
    code.push_str("// status_code: HTTP status code\n");
    code.push_str("// html_body: HTML string body\n");
    code.push_str("// Returns: Complete HTTP response (caller must free)\n");
    code.push_str("char* http_HTMLResponse(int status_code, const char* html_body) {\n");
    code.push_str("    return http_make_response(status_code, \"text/html\", html_body);\n");
    code.push_str("}\n\n");
    
    code
}
