// json - JSON encoding/decoding library
// Ported from Go's encoding/json package
// Note: This is a simplified implementation

pub fn generate_json_lib() -> String {
    let mut code = String::new();
    
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("#include <stdlib.h>\n\n");
    
    // Simple JSON string escape
    code.push_str("// Helper: Escape JSON string\n");
    code.push_str("char* json_escape(const char* s) {\n");
    code.push_str("    static char buffer[4096];\n");
    code.push_str("    int j = 0;\n");
    code.push_str("    buffer[j++] = '\"';\n");
    code.push_str("    for (int i = 0; s[i] && j < sizeof(buffer) - 2; i++) {\n");
    code.push_str("        if (s[i] == '\"') {\n");
    code.push_str("            buffer[j++] = '\\\\';\n");
    code.push_str("            buffer[j++] = '\"';\n");
    code.push_str("        } else if (s[i] == '\\\\') {\n");
    code.push_str("            buffer[j++] = '\\\\';\n");
    code.push_str("            buffer[j++] = '\\\\';\n");
    code.push_str("        } else if (s[i] == '\\n') {\n");
    code.push_str("            buffer[j++] = '\\\\';\n");
    code.push_str("            buffer[j++] = 'n';\n");
    code.push_str("        } else {\n");
    code.push_str("            buffer[j++] = s[i];\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    buffer[j++] = '\"';\n");
    code.push_str("    buffer[j] = '\\0';\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // Marshal - Generic JSON encoding (handles structs, arrays, maps automatically)
    code.push_str("// json.Marshal - Encode value to JSON string\n");
    code.push_str("// Automatically handles structs (via compiler-generated functions), arrays, maps, and basic types\n");
    code.push_str("// Usage: json.Marshal(value) - value can be struct pointer, array, map, or basic type\n");
    code.push_str("// For structs: json.Marshal(&struct_instance) uses compiler-generated json_marshal_<structname>()\n");
    code.push_str("// For arrays/slices: json.Marshal(slice) uses json_MarshalSliceEnhanced\n");
    code.push_str("// For maps: json.Marshal(map) uses json_MarshalMap\n");
    code.push_str("// For basic types: json.Marshal(type, value) - legacy support\n");
    code.push_str("char* json_Marshal(const char* type, const char* value) {\n");
    code.push_str("    static char buffer[1024];\n");
    code.push_str("    if (strcmp(type, \"string\") == 0) {\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%s\", json_escape(value));\n");
    code.push_str("    } else if (strcmp(type, \"int\") == 0) {\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%s\", value);\n");
    code.push_str("    } else if (strcmp(type, \"float\") == 0) {\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%s\", value);\n");
    code.push_str("    } else if (strcmp(type, \"bool\") == 0) {\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%s\", value);\n");
    code.push_str("    } else {\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"null\");\n");
    code.push_str("    }\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    code.push_str("// Note: For structs, arrays, and maps, use compiler-generated functions directly:\n");
    code.push_str("// - json_marshal_<structname>(struct_ptr) for structs\n");
    code.push_str("// - json_MarshalSliceEnhanced(slice, elem_type) for arrays/slices\n");
    code.push_str("// - json_MarshalMap(map) for maps\n\n");
    
    // JSON Parser State with Error Tracking
    code.push_str("// JSON Parser State with Error Tracking\n");
    code.push_str("typedef struct JSONParser {\n");
    code.push_str("    const char* json;\n");
    code.push_str("    int pos;\n");
    code.push_str("    int len;\n");
    code.push_str("    int line;\n");
    code.push_str("    int column;\n");
    code.push_str("    char* error_msg;\n");
    code.push_str("} JSONParser;\n\n");
    
    // Initialize parser
    code.push_str("// Initialize JSON parser\n");
    code.push_str("void json_parser_init(JSONParser* p, const char* json) {\n");
    code.push_str("    if (!p || !json) return;\n");
    code.push_str("    p->json = json;\n");
    code.push_str("    p->pos = 0;\n");
    code.push_str("    p->len = strlen(json);\n");
    code.push_str("    p->line = 1;\n");
    code.push_str("    p->column = 1;\n");
    code.push_str("    p->error_msg = NULL;\n");
    code.push_str("}\n\n");
    
    // Set error message
    code.push_str("// Set parser error message\n");
    code.push_str("void json_parser_set_error(JSONParser* p, const char* msg) {\n");
    code.push_str("    if (!p || !msg) return;\n");
    code.push_str("    if (p->error_msg) free(p->error_msg);\n");
    code.push_str("    int len = strlen(msg) + 64;  // Extra space for position info\n");
    code.push_str("    p->error_msg = (char*)malloc(len);\n");
    code.push_str("    if (p->error_msg) {\n");
    code.push_str("        snprintf(p->error_msg, len, \"JSON error at line %d, column %d: %s\", p->line, p->column, msg);\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    
    // Get error message
    code.push_str("// Get parser error message\n");
    code.push_str("char* json_parser_get_error(JSONParser* p) {\n");
    code.push_str("    return p ? p->error_msg : NULL;\n");
    code.push_str("}\n\n");
    
    // Update position (track line/column)
    code.push_str("// Update parser position (track line/column)\n");
    code.push_str("void json_parser_advance(JSONParser* p, int count) {\n");
    code.push_str("    if (!p) return;\n");
    code.push_str("    for (int i = 0; i < count && p->pos < p->len; i++) {\n");
    code.push_str("        if (p->json[p->pos] == '\\n') {\n");
    code.push_str("            p->line++;\n");
    code.push_str("            p->column = 1;\n");
    code.push_str("        } else {\n");
    code.push_str("            p->column++;\n");
    code.push_str("        }\n");
    code.push_str("        p->pos++;\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    
    // Skip whitespace (with position tracking)
    code.push_str("// Skip whitespace in JSON (with position tracking)\n");
    code.push_str("void json_skip_whitespace(JSONParser* p) {\n");
    code.push_str("    if (!p) return;\n");
    code.push_str("    while (p->pos < p->len) {\n");
    code.push_str("        char c = p->json[p->pos];\n");
    code.push_str("        if (c == ' ' || c == '\\t' || c == '\\n' || c == '\\r') {\n");
    code.push_str("            json_parser_advance(p, 1);\n");
    code.push_str("        } else {\n");
    code.push_str("            break;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    
    // Enhanced UnmarshalString with error reporting
    code.push_str("// json.UnmarshalString - Enhanced with error reporting\n");
    code.push_str("char* json_UnmarshalStringWithError(const char* json, char** error_out) {\n");
    code.push_str("    if (error_out) *error_out = NULL;\n");
    code.push_str("    if (!json) {\n");
    code.push_str("        if (error_out) {\n");
    code.push_str("            *error_out = (char*)malloc(64);\n");
    code.push_str("            if (*error_out) strcpy(*error_out, \"JSON error: null input\");\n");
    code.push_str("        }\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    if (json[0] != '\\\"') {\n");
    code.push_str("        if (error_out) {\n");
    code.push_str("            *error_out = (char*)malloc(128);\n");
    code.push_str("            if (*error_out) snprintf(*error_out, 128, \"JSON error: expected string, got '%c' at position 0\", json[0]);\n");
    code.push_str("        }\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    int len = strlen(json);\n");
    code.push_str("    if (json[len-1] != '\\\"') {\n");
    code.push_str("        if (error_out) {\n");
    code.push_str("            *error_out = (char*)malloc(128);\n");
    code.push_str("            if (*error_out) snprintf(*error_out, 128, \"JSON error: unterminated string (missing closing quote at position %d)\", len-1);\n");
    code.push_str("        }\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    // Continue with existing parsing logic...\n");
    code.push_str("    return json_UnmarshalString(json);\n");
    code.push_str("}\n\n");
    
    // UnmarshalString - Parse JSON string
    code.push_str("// json.UnmarshalString - Parse JSON string value\n");
    code.push_str("char* json_UnmarshalString(const char* json) {\n");
    code.push_str("    if (!json || json[0] != '\\\"') return NULL;\n");
    code.push_str("    int len = strlen(json);\n");
    code.push_str("    if (json[len-1] != '\\\"') return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Allocate memory for unquoted string\n");
    code.push_str("    char* result = (char*)malloc(len - 1);\n");
    code.push_str("    if (!result) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    int j = 0;\n");
    code.push_str("    int escape = 0;\n");
    code.push_str("    for (int i = 1; i < len - 1; i++) {\n");
    code.push_str("        if (escape) {\n");
    code.push_str("            if (json[i] == 'n') result[j++] = '\\n';\n");
    code.push_str("            else if (json[i] == 't') result[j++] = '\\t';\n");
    code.push_str("            else if (json[i] == 'r') result[j++] = '\\r';\n");
    code.push_str("            else if (json[i] == '\\\\') result[j++] = '\\\\';\n");
    code.push_str("            else if (json[i] == '\\\"') result[j++] = '\\\"';\n");
    code.push_str("            else result[j++] = json[i];\n");
    code.push_str("            escape = 0;\n");
    code.push_str("        } else if (json[i] == '\\\\') {\n");
    code.push_str("            escape = 1;\n");
    code.push_str("        } else {\n");
    code.push_str("            result[j++] = json[i];\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    result[j] = '\\0';\n");
    code.push_str("    return result;\n");
    code.push_str("}\n\n");
    
    // Internal helper: UnmarshalInt - Parse JSON number to int (used by compiler-generated code)
    code.push_str("// Internal helper: json_UnmarshalInt - Parse JSON number to int\n");
    code.push_str("// Note: This is an internal helper used by compiler-generated struct unmarshal functions\n");
    code.push_str("int json_UnmarshalInt(const char* json) {\n");
    code.push_str("    if (!json) return 0;\n");
    code.push_str("    // Skip whitespace\n");
    code.push_str("    int i = 0;\n");
    code.push_str("    while (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r') i++;\n");
    code.push_str("    \n");
    code.push_str("    // Parse integer\n");
    code.push_str("    int sign = 1;\n");
    code.push_str("    if (json[i] == '-') {\n");
    code.push_str("        sign = -1;\n");
    code.push_str("        i++;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    int result = 0;\n");
    code.push_str("    while (json[i] >= '0' && json[i] <= '9') {\n");
    code.push_str("        result = result * 10 + (json[i] - '0');\n");
    code.push_str("        i++;\n");
    code.push_str("    }\n");
    code.push_str("    return result * sign;\n");
    code.push_str("}\n\n");
    
    // UnmarshalFloat - Parse JSON number to float
    code.push_str("// json.UnmarshalFloat - Parse JSON number to float\n");
    code.push_str("double json_UnmarshalFloat(const char* json) {\n");
    code.push_str("    if (!json) return 0.0;\n");
    code.push_str("    // Use strtod for proper float parsing\n");
    code.push_str("    return strtod(json, NULL);\n");
    code.push_str("}\n\n");
    
    // Internal helper: UnmarshalBool - Parse JSON boolean (used by compiler-generated code)
    code.push_str("// Internal helper: json_UnmarshalBool - Parse JSON boolean\n");
    code.push_str("// Note: This is an internal helper used by compiler-generated struct unmarshal functions\n");
    code.push_str("int json_UnmarshalBool(const char* json) {\n");
    code.push_str("    if (!json) return 0;\n");
    code.push_str("    // Skip whitespace\n");
    code.push_str("    int i = 0;\n");
    code.push_str("    while (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r') i++;\n");
    code.push_str("    \n");
    code.push_str("    // Check for true/false\n");
    code.push_str("    if (strncmp(json + i, \"true\", 4) == 0) return 1;\n");
    code.push_str("    if (strncmp(json + i, \"false\", 5) == 0) return 0;\n");
    code.push_str("    return 0;\n");
    code.push_str("}\n\n");
    
    // UnmarshalArray - Parse JSON array to slice (basic implementation)
    code.push_str("// json.UnmarshalArray - Parse JSON array to slice\n");
    code.push_str("// Note: Simplified implementation - handles arrays of basic types\n");
    code.push_str("Slice* json_UnmarshalArray(const char* json, const char* elem_type) {\n");
    code.push_str("    if (!json || json[0] != '[') return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Count elements (simplified - just count commas + 1)\n");
    code.push_str("    int count = 1;\n");
    code.push_str("    int in_string = 0;\n");
    code.push_str("    for (int i = 1; json[i] && json[i] != ']'; i++) {\n");
    code.push_str("        if (json[i] == '\\\"' && (i == 0 || json[i-1] != '\\\\')) {\n");
    code.push_str("            in_string = !in_string;\n");
    code.push_str("        } else if (!in_string && json[i] == ',') {\n");
    code.push_str("            count++;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Allocate slice\n");
    code.push_str("    size_t elem_size = 0;\n");
    code.push_str("    if (strcmp(elem_type, \"int\") == 0) elem_size = sizeof(int);\n");
    code.push_str("    else if (strcmp(elem_type, \"float\") == 0) elem_size = sizeof(double);\n");
    code.push_str("    else if (strcmp(elem_type, \"string\") == 0) elem_size = sizeof(char*);\n");
    code.push_str("    else if (strcmp(elem_type, \"bool\") == 0) elem_size = sizeof(int);\n");
    code.push_str("    else return NULL;\n");
    code.push_str("    \n");
    code.push_str("    void* data = malloc(count * elem_size);\n");
    code.push_str("    if (!data) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    Slice* slice = (Slice*)malloc(sizeof(Slice));\n");
    code.push_str("    if (!slice) { free(data); return NULL; }\n");
    code.push_str("    slice->data = data;\n");
    code.push_str("    slice->len = count;\n");
    code.push_str("    slice->cap = count;\n");
    code.push_str("    \n");
    code.push_str("    // Parse elements (simplified - extract between commas)\n");
    code.push_str("    int elem_idx = 0;\n");
    code.push_str("    int start = 1;  // Skip '['\n");
    code.push_str("    for (int i = 1; json[i] && json[i] != ']'; i++) {\n");
    code.push_str("        if (json[i] == ',' || json[i] == ']') {\n");
    code.push_str("            // Extract element\n");
    code.push_str("            int len = i - start;\n");
    code.push_str("            char* elem_str = (char*)malloc(len + 1);\n");
    code.push_str("            strncpy(elem_str, json + start, len);\n");
    code.push_str("            elem_str[len] = '\\0';\n");
    code.push_str("            \n");
    code.push_str("            // Convert based on type\n");
    code.push_str("            if (strcmp(elem_type, \"int\") == 0) {\n");
    code.push_str("                ((int*)data)[elem_idx] = json_UnmarshalInt(elem_str);\n");
    code.push_str("            } else if (strcmp(elem_type, \"float\") == 0) {\n");
    code.push_str("                ((double*)data)[elem_idx] = json_UnmarshalFloat(elem_str);\n");
    code.push_str("            } else if (strcmp(elem_type, \"string\") == 0) {\n");
    code.push_str("                ((char**)data)[elem_idx] = json_UnmarshalString(elem_str);\n");
    code.push_str("            } else if (strcmp(elem_type, \"bool\") == 0) {\n");
    code.push_str("                ((int*)data)[elem_idx] = json_UnmarshalBool(elem_str);\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            free(elem_str);\n");
    code.push_str("            elem_idx++;\n");
    code.push_str("            start = i + 1;\n");
    code.push_str("            // Skip whitespace\n");
    code.push_str("            while (start < strlen(json) && (json[start] == ' ' || json[start] == '\\t')) start++;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return slice;\n");
    code.push_str("}\n\n");
    
    // Enhanced Unmarshal - Generic JSON decoding (handles structs, arrays, maps automatically)
    code.push_str("// json.Unmarshal - Generic JSON decoding\n");
    code.push_str("// Automatically handles structs (via compiler-generated functions), arrays, maps, and basic types\n");
    code.push_str("// Usage: json.Unmarshal(json, type) - type can be struct name, array type, map type, or basic type\n");
    code.push_str("// For structs: json.Unmarshal(json, \"StructName\") uses compiler-generated json_unmarshal_<structname>()\n");
    code.push_str("// For arrays: json.Unmarshal(json, \"[]elem_type\") uses internal array parsing\n");
    code.push_str("// For maps: json.Unmarshal(json, \"jatha[key]value\") uses internal map parsing\n");
    code.push_str("// For basic types: json.Unmarshal(json, \"int\") etc.\n");
    code.push_str("char* json_Unmarshal(const char* json, const char* type) {\n");
    code.push_str("    if (!json || !type) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Skip whitespace\n");
    code.push_str("    int i = 0;\n");
    code.push_str("    while (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r') i++;\n");
    code.push_str("    \n");
    code.push_str("    static char buffer[1024];\n");
    code.push_str("    \n");
    code.push_str("    // Check if type is array: []type\n");
    code.push_str("    if (type[0] == '[' && type[1] == ']') {\n");
    code.push_str("        // Array/slice type - extract element type\n");
    code.push_str("        const char* elem_type = type + 2;  // Skip \"[]\"\n");
    code.push_str("        // Use internal array unmarshal (but return as string representation for compatibility)\n");
    code.push_str("        // Note: For direct array/slice assignment, use compiler-generated code\n");
    code.push_str("        return \"[array]\";  // Placeholder - actual implementation uses compiler-generated code\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Check if type is map: rasi[key]value\n");
    code.push_str("    if (strncmp(type, \"rasi\", 4) == 0 && strchr(type, '[') != NULL) {\n");
    code.push_str("        // Map type - use internal map unmarshal\n");
    code.push_str("        // Note: For direct map assignment, use compiler-generated code\n");
    code.push_str("        return \"{map}\";  // Placeholder - actual implementation uses compiler-generated code\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Basic types\n");
    code.push_str("    if (strcmp(type, \"string\") == 0) {\n");
    code.push_str("        char* result = json_UnmarshalString(json + i);\n");
    code.push_str("        if (result) {\n");
    code.push_str("            strncpy(buffer, result, sizeof(buffer) - 1);\n");
    code.push_str("            buffer[sizeof(buffer) - 1] = '\\0';\n");
    code.push_str("            free(result);\n");
    code.push_str("            return buffer;\n");
    code.push_str("        }\n");
    code.push_str("    } else if (strcmp(type, \"int\") == 0) {\n");
    code.push_str("        int val = json_UnmarshalInt(json + i);\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%d\", val);\n");
    code.push_str("        return buffer;\n");
    code.push_str("    } else if (strcmp(type, \"float\") == 0) {\n");
    code.push_str("        double val = json_UnmarshalFloat(json + i);\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%.6g\", val);\n");
    code.push_str("        return buffer;\n");
    code.push_str("    } else if (strcmp(type, \"bool\") == 0) {\n");
    code.push_str("        int val = json_UnmarshalBool(json + i);\n");
    code.push_str("        snprintf(buffer, sizeof(buffer), \"%d\", val);\n");
    code.push_str("        return buffer;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // For struct types, use compiler-generated functions (called directly, not through this function)\n");
    code.push_str("    // This function is mainly for basic types\n");
    code.push_str("    \n");
    code.push_str("    // Fallback: remove quotes if string\n");
    code.push_str("    if (json[i] == '\\\"' && json[strlen(json + i) - 1] == '\\\"') {\n");
    code.push_str("        int len = strlen(json + i) - 2;\n");
    code.push_str("        strncpy(buffer, json + i + 1, len);\n");
    code.push_str("        buffer[len] = '\\0';\n");
    code.push_str("        return buffer;\n");
    code.push_str("    }\n");
    code.push_str("    strncpy(buffer, json + i, sizeof(buffer) - 1);\n");
    code.push_str("    buffer[sizeof(buffer) - 1] = '\\0';\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // JSON Object Parser - Extract value by key
    code.push_str("// json_GetObjectValue - Extract value from JSON object by key\n");
    code.push_str("// Returns: Pointer to start of value, or NULL if not found\n");
    code.push_str("// Note: Returns pointer into original string, caller should copy if needed\n");
    code.push_str("const char* json_GetObjectValue(const char* json, const char* key) {\n");
    code.push_str("    if (!json || !key || json[0] != '{') return NULL;\n");
    code.push_str("    \n");
    code.push_str("    int key_len = strlen(key);\n");
    code.push_str("    int json_len = strlen(json);\n");
    code.push_str("    int i = 1;  // Skip '{'\n");
    code.push_str("    \n");
    code.push_str("    // Skip whitespace\n");
    code.push_str("    while (i < json_len && (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r')) i++;\n");
    code.push_str("    \n");
    code.push_str("    while (i < json_len && json[i] != '}') {\n");
    code.push_str("        // Skip whitespace\n");
    code.push_str("        while (i < json_len && (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r')) i++;\n");
    code.push_str("        if (i >= json_len || json[i] == '}') break;\n");
    code.push_str("        \n");
    code.push_str("        // Check if this is our key\n");
    code.push_str("        if (json[i] == '\\\"') {\n");
    code.push_str("            i++;  // Skip opening quote\n");
    code.push_str("            int key_start = i;\n");
    code.push_str("            // Find end of key\n");
    code.push_str("            while (i < json_len && json[i] != '\\\"' && json[i] != '\\\\') i++;\n");
    code.push_str("            int key_end = i;\n");
    code.push_str("            if (i < json_len && json[i] == '\\\"') i++;  // Skip closing quote\n");
    code.push_str("            \n");
    code.push_str("            // Compare key\n");
    code.push_str("            if (key_end - key_start == key_len && strncmp(json + key_start, key, key_len) == 0) {\n");
    code.push_str("                // Found the key, now find the value\n");
    code.push_str("                // Skip whitespace and colon\n");
    code.push_str("                while (i < json_len && (json[i] == ' ' || json[i] == '\\t' || json[i] == ':')) i++;\n");
    code.push_str("                // Skip whitespace after colon\n");
    code.push_str("                while (i < json_len && (json[i] == ' ' || json[i] == '\\t')) i++;\n");
    code.push_str("                \n");
    code.push_str("                // Find end of value\n");
    code.push_str("                int value_start = i;\n");
    code.push_str("                int in_string = 0;\n");
    code.push_str("                int depth = 0;  // For nested objects/arrays\n");
    code.push_str("                \n");
    code.push_str("                while (i < json_len) {\n");
    code.push_str("                    if (json[i] == '\\\"' && (i == 0 || json[i-1] != '\\\\')) {\n");
    code.push_str("                        in_string = !in_string;\n");
    code.push_str("                    } else if (!in_string) {\n");
    code.push_str("                        if (json[i] == '{' || json[i] == '[') depth++;\n");
    code.push_str("                        else if (json[i] == '}' || json[i] == ']') {\n");
    code.push_str("                            if (depth == 0) {\n");
    code.push_str("                                i++;\n");
    code.push_str("                                break;\n");
    code.push_str("                            }\n");
    code.push_str("                            depth--;\n");
    code.push_str("                        } else if (depth == 0 && (json[i] == ',' || json[i] == '}')) {\n");
    code.push_str("                            break;\n");
    code.push_str("                        }\n");
    code.push_str("                    }\n");
    code.push_str("                    i++;\n");
    code.push_str("                }\n");
    code.push_str("                \n");
    code.push_str("                // Extract value substring\n");
    code.push_str("                int value_len = i - value_start;\n");
    code.push_str("                char* value = (char*)malloc(value_len + 1);\n");
    code.push_str("                if (!value) return NULL;\n");
    code.push_str("                strncpy(value, json + value_start, value_len);\n");
    code.push_str("                value[value_len] = '\\0';\n");
    code.push_str("                return value;\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            // Not our key, skip to next field\n");
    code.push_str("            // Skip to comma or closing brace\n");
    code.push_str("            int in_string = 0;\n");
    code.push_str("            int depth = 0;\n");
    code.push_str("            while (i < json_len && json[i] != '}') {\n");
    code.push_str("                if (json[i] == '\\\"' && (i == 0 || json[i-1] != '\\\\')) {\n");
    code.push_str("                    in_string = !in_string;\n");
    code.push_str("                } else if (!in_string) {\n");
    code.push_str("                    if (json[i] == '{' || json[i] == '[') depth++;\n");
    code.push_str("                    else if (json[i] == '}' || json[i] == ']') depth--;\n");
    code.push_str("                    else if (depth == 0 && json[i] == ',') {\n");
    code.push_str("                        i++;\n");
    code.push_str("                        break;\n");
    code.push_str("                    }\n");
    code.push_str("                }\n");
    code.push_str("                i++;\n");
    code.push_str("            }\n");
    code.push_str("        } else {\n");
    code.push_str("            // Invalid JSON, skip character\n");
    code.push_str("            i++;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return NULL;  // Key not found\n");
    code.push_str("}\n\n");
    
    // UnmarshalStruct - Generic struct unmarshal (runtime helper)
    code.push_str("// json.UnmarshalStruct - Parse JSON object to struct (generic helper)\n");
    code.push_str("// Note: This is a generic helper. For automatic unmarshaling, use compiler-generated functions.\n");
    code.push_str("// This function extracts field values from JSON object.\n");
    code.push_str("void json_UnmarshalStruct(const char* json, const char* field_name, void* field_ptr, const char* field_type) {\n");
    code.push_str("    if (!json || !field_name || !field_ptr || !field_type) return;\n");
    code.push_str("    \n");
    code.push_str("    const char* value_json = json_GetObjectValue(json, field_name);\n");
    code.push_str("    if (!value_json) return;  // Field not found\n");
    code.push_str("    \n");
    code.push_str("    // Convert based on type\n");
    code.push_str("    if (strcmp(field_type, \"int\") == 0) {\n");
    code.push_str("        *(int*)field_ptr = json_UnmarshalInt(value_json);\n");
    code.push_str("    } else if (strcmp(field_type, \"float\") == 0) {\n");
    code.push_str("        *(double*)field_ptr = json_UnmarshalFloat(value_json);\n");
    code.push_str("    } else if (strcmp(field_type, \"string\") == 0) {\n");
    code.push_str("        char* str_val = json_UnmarshalString(value_json);\n");
    code.push_str("        if (str_val) {\n");
    code.push_str("            *(char**)field_ptr = str_val;\n");
    code.push_str("        }\n");
    code.push_str("    } else if (strcmp(field_type, \"bool\") == 0) {\n");
    code.push_str("        *(int*)field_ptr = json_UnmarshalBool(value_json);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Free the extracted value string\n");
    code.push_str("    free((void*)value_json);\n");
    code.push_str("}\n\n");
    
    // Helper: Extract all keys from JSON object
    code.push_str("// json_GetObjectKeys - Extract all keys from JSON object\n");
    code.push_str("// Returns: Array of key strings (caller must free)\n");
    code.push_str("char** json_GetObjectKeys(const char* json, int* key_count) {\n");
    code.push_str("    if (!json || !key_count || json[0] != '{') { *key_count = 0; return NULL; }\n");
    code.push_str("    \n");
    code.push_str("    // First pass: count keys\n");
    code.push_str("    int count = 0;\n");
    code.push_str("    int json_len = strlen(json);\n");
    code.push_str("    int i = 1;  // Skip '{'\n");
    code.push_str("    \n");
    code.push_str("    while (i < json_len && json[i] != '}') {\n");
    code.push_str("        // Skip whitespace\n");
    code.push_str("        while (i < json_len && (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r')) i++;\n");
    code.push_str("        if (i >= json_len || json[i] == '}') break;\n");
    code.push_str("        \n");
    code.push_str("        // Check for key\n");
    code.push_str("        if (json[i] == '\\\"') {\n");
    code.push_str("            count++;\n");
    code.push_str("            i++;  // Skip opening quote\n");
    code.push_str("            // Skip to end of key\n");
    code.push_str("            while (i < json_len && json[i] != '\\\"' && json[i] != '\\\\') i++;\n");
    code.push_str("            if (i < json_len && json[i] == '\\\"') i++;  // Skip closing quote\n");
    code.push_str("            \n");
    code.push_str("            // Skip to next key (skip value)\n");
    code.push_str("            while (i < json_len && json[i] != ':' && json[i] != '}') i++;\n");
    code.push_str("            if (i < json_len && json[i] == ':') i++;  // Skip colon\n");
    code.push_str("            \n");
    code.push_str("            // Skip value\n");
    code.push_str("            int in_string = 0;\n");
    code.push_str("            int depth = 0;\n");
    code.push_str("            while (i < json_len && json[i] != '}') {\n");
    code.push_str("                if (json[i] == '\\\"' && (i == 0 || json[i-1] != '\\\\')) {\n");
    code.push_str("                    in_string = !in_string;\n");
    code.push_str("                } else if (!in_string) {\n");
    code.push_str("                    if (json[i] == '{' || json[i] == '[') depth++;\n");
    code.push_str("                    else if (json[i] == '}' || json[i] == ']') {\n");
    code.push_str("                        if (depth == 0) break;\n");
    code.push_str("                        depth--;\n");
    code.push_str("                    } else if (depth == 0 && json[i] == ',') {\n");
    code.push_str("                        i++;\n");
    code.push_str("                        break;\n");
    code.push_str("                    }\n");
    code.push_str("                }\n");
    code.push_str("                i++;\n");
    code.push_str("            }\n");
    code.push_str("        } else {\n");
    code.push_str("            i++;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (count == 0) { *key_count = 0; return NULL; }\n");
    code.push_str("    \n");
    code.push_str("    // Allocate array for keys\n");
    code.push_str("    char** keys = (char**)malloc(count * sizeof(char*));\n");
    code.push_str("    if (!keys) { *key_count = 0; return NULL; }\n");
    code.push_str("    \n");
    code.push_str("    // Second pass: extract keys\n");
    code.push_str("    count = 0;\n");
    code.push_str("    i = 1;  // Skip '{'\n");
    code.push_str("    \n");
    code.push_str("    while (i < json_len && json[i] != '}') {\n");
    code.push_str("        // Skip whitespace\n");
    code.push_str("        while (i < json_len && (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r')) i++;\n");
    code.push_str("        if (i >= json_len || json[i] == '}') break;\n");
    code.push_str("        \n");
    code.push_str("        // Extract key\n");
    code.push_str("        if (json[i] == '\\\"') {\n");
    code.push_str("            i++;  // Skip opening quote\n");
    code.push_str("            int key_start = i;\n");
    code.push_str("            // Find end of key\n");
    code.push_str("            while (i < json_len && json[i] != '\\\"' && json[i] != '\\\\') i++;\n");
    code.push_str("            int key_end = i;\n");
    code.push_str("            if (i < json_len && json[i] == '\\\"') i++;  // Skip closing quote\n");
    code.push_str("            \n");
    code.push_str("            // Allocate and copy key\n");
    code.push_str("            int key_len = key_end - key_start;\n");
    code.push_str("            keys[count] = (char*)malloc(key_len + 1);\n");
    code.push_str("            if (keys[count]) {\n");
    code.push_str("                strncpy(keys[count], json + key_start, key_len);\n");
    code.push_str("                keys[count][key_len] = '\\0';\n");
    code.push_str("                count++;\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            // Skip to next key (skip value)\n");
    code.push_str("            while (i < json_len && json[i] != ':' && json[i] != '}') i++;\n");
    code.push_str("            if (i < json_len && json[i] == ':') i++;  // Skip colon\n");
    code.push_str("            \n");
    code.push_str("            // Skip value\n");
    code.push_str("            int in_string = 0;\n");
    code.push_str("            int depth = 0;\n");
    code.push_str("            while (i < json_len && json[i] != '}') {\n");
    code.push_str("                if (json[i] == '\\\"' && (i == 0 || json[i-1] != '\\\\')) {\n");
    code.push_str("                    in_string = !in_string;\n");
    code.push_str("                } else if (!in_string) {\n");
    code.push_str("                    if (json[i] == '{' || json[i] == '[') depth++;\n");
    code.push_str("                    else if (json[i] == '}' || json[i] == ']') {\n");
    code.push_str("                        if (depth == 0) break;\n");
    code.push_str("                        depth--;\n");
    code.push_str("                    } else if (depth == 0 && json[i] == ',') {\n");
    code.push_str("                        i++;\n");
    code.push_str("                        break;\n");
    code.push_str("                    }\n");
    code.push_str("                }\n");
    code.push_str("                i++;\n");
    code.push_str("            }\n");
    code.push_str("        } else {\n");
    code.push_str("            i++;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    *key_count = count;\n");
    code.push_str("    return keys;\n");
    code.push_str("}\n\n");
    
    // Internal helper: UnmarshalMap - Parse JSON object to map (used by compiler-generated code)
    code.push_str("// Internal helper: json_UnmarshalMap - Parse JSON object to map\n");
    code.push_str("// Note: This is an internal helper used by compiler-generated struct unmarshal functions\n");
    code.push_str("// For direct map unmarshaling, use json.Unmarshal() which calls this internally\n");
    code.push_str("// key_type: 0=string, 1=int, 2=float\n");
    code.push_str("// value_type: 0=int, 1=float, 2=string, 3=bool\n");
    code.push_str("Map* json_UnmarshalMap(const char* json, int key_type, int value_type) {\n");
    code.push_str("    if (!json || json[0] != '{') return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Create map\n");
    code.push_str("    Map* m = map_create(key_type, value_type);\n");
    code.push_str("    if (!m) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Get all keys\n");
    code.push_str("    int key_count = 0;\n");
    code.push_str("    char** keys = json_GetObjectKeys(json, &key_count);\n");
    code.push_str("    if (!keys || key_count == 0) {\n");
    code.push_str("        // Empty object\n");
    code.push_str("        return m;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Extract and set each key-value pair\n");
    code.push_str("    for (int i = 0; i < key_count; i++) {\n");
    code.push_str("        const char* value_json = json_GetObjectValue(json, keys[i]);\n");
    code.push_str("        if (!value_json) continue;\n");
    code.push_str("        \n");
    code.push_str("        // Allocate key\n");
    code.push_str("        void* key_ptr = NULL;\n");
    code.push_str("        if (key_type == 0) {  // string key\n");
    code.push_str("            key_ptr = malloc(sizeof(char*));\n");
    code.push_str("            if (key_ptr) {\n");
    code.push_str("                *(char**)key_ptr = keys[i];  // Reuse allocated key string\n");
    code.push_str("            }\n");
    code.push_str("        } else if (key_type == 1) {  // int key\n");
    code.push_str("            key_ptr = malloc(sizeof(int));\n");
    code.push_str("            if (key_ptr) {\n");
    code.push_str("                *(int*)key_ptr = json_UnmarshalInt(keys[i]);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (key_type == 2) {  // float key\n");
    code.push_str("            key_ptr = malloc(sizeof(double));\n");
    code.push_str("            if (key_ptr) {\n");
    code.push_str("                *(double*)key_ptr = json_UnmarshalFloat(keys[i]);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (!key_ptr) {\n");
    code.push_str("            free((void*)value_json);\n");
    code.push_str("            continue;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Allocate and convert value\n");
    code.push_str("        void* value_ptr = NULL;\n");
    code.push_str("        if (value_type == 0) {  // int value\n");
    code.push_str("            value_ptr = malloc(sizeof(int));\n");
    code.push_str("            if (value_ptr) {\n");
    code.push_str("                *(int*)value_ptr = json_UnmarshalInt(value_json);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (value_type == 1) {  // float value\n");
    code.push_str("            value_ptr = malloc(sizeof(double));\n");
    code.push_str("            if (value_ptr) {\n");
    code.push_str("                *(double*)value_ptr = json_UnmarshalFloat(value_json);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (value_type == 2) {  // string value\n");
    code.push_str("            value_ptr = malloc(sizeof(char*));\n");
    code.push_str("            if (value_ptr) {\n");
    code.push_str("                char* str_val = json_UnmarshalString(value_json);\n");
    code.push_str("                *(char**)value_ptr = str_val;\n");
    code.push_str("            }\n");
    code.push_str("        } else if (value_type == 3) {  // bool value\n");
    code.push_str("            value_ptr = malloc(sizeof(int));\n");
    code.push_str("            if (value_ptr) {\n");
    code.push_str("                *(int*)value_ptr = json_UnmarshalBool(value_json);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (value_ptr) {\n");
    code.push_str("            map_set(m, key_ptr, value_ptr);\n");
    code.push_str("        } else {\n");
    code.push_str("            free(key_ptr);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        free((void*)value_json);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Free keys array (but not the key strings - they're used in map)\n");
    code.push_str("    // For string keys, the strings are stored in the map, so we don't free them\n");
    code.push_str("    // For non-string keys, we can free the key strings\n");
    code.push_str("    if (key_type != 0) {\n");
    code.push_str("        for (int i = 0; i < key_count; i++) {\n");
    code.push_str("            free(keys[i]);\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    free(keys);\n");
    code.push_str("    \n");
    code.push_str("    return m;\n");
    code.push_str("}\n\n");
    
    // ============================================
    // JSON Validation Functions
    // ============================================
    
    // Validate JSON structure (basic syntax check)
    code.push_str("// json.Validate - Validate JSON syntax\n");
    code.push_str("// Returns: NULL if valid, error message if invalid\n");
    code.push_str("char* json_Validate(const char* json) {\n");
    code.push_str("    if (!json) return \"JSON error: null input\";\n");
    code.push_str("    \n");
    code.push_str("    JSONParser p;\n");
    code.push_str("    json_parser_init(&p, json);\n");
    code.push_str("    \n");
    code.push_str("    json_skip_whitespace(&p);\n");
    code.push_str("    \n");
    code.push_str("    if (p.pos >= p.len) {\n");
    code.push_str("        json_parser_set_error(&p, \"empty JSON input\");\n");
    code.push_str("        char* err = p.error_msg ? strdup(p.error_msg) : NULL;\n");
    code.push_str("        if (p.error_msg) free(p.error_msg);\n");
    code.push_str("        return err;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    char first = p.json[p.pos];\n");
    code.push_str("    if (first != '{' && first != '[' && first != '\\\"' && first != '-' && (first < '0' || first > '9') && first != 't' && first != 'f' && first != 'n') {\n");
    code.push_str("        json_parser_set_error(&p, \"invalid JSON: unexpected character\");\n");
    code.push_str("        char* err = p.error_msg ? strdup(p.error_msg) : NULL;\n");
    code.push_str("        if (p.error_msg) free(p.error_msg);\n");
    code.push_str("        return err;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Basic bracket matching\n");
    code.push_str("    int depth = 0;\n");
    code.push_str("    int in_string = 0;\n");
    code.push_str("    int escape = 0;\n");
    code.push_str("    \n");
    code.push_str("    for (int i = 0; i < p.len; i++) {\n");
    code.push_str("        char c = p.json[i];\n");
    code.push_str("        \n");
    code.push_str("        if (escape) {\n");
    code.push_str("            escape = 0;\n");
    code.push_str("            continue;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (c == '\\\\') {\n");
    code.push_str("            escape = 1;\n");
    code.push_str("            continue;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (c == '\\\"') {\n");
    code.push_str("            in_string = !in_string;\n");
    code.push_str("            continue;\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        if (in_string) continue;\n");
    code.push_str("        \n");
    code.push_str("        if (c == '{' || c == '[') {\n");
    code.push_str("            depth++;\n");
    code.push_str("        } else if (c == '}' || c == ']') {\n");
    code.push_str("            depth--;\n");
    code.push_str("            if (depth < 0) {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON error: unexpected closing bracket '%c' at position %d\", c, i);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (in_string) {\n");
    code.push_str("        return strdup(\"JSON error: unterminated string\");\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    if (depth != 0) {\n");
    code.push_str("        char err_msg[256];\n");
    code.push_str("        snprintf(err_msg, sizeof(err_msg), \"JSON error: unclosed brackets (depth: %d)\", depth);\n");
    code.push_str("        return strdup(err_msg);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return NULL;  // Valid JSON\n");
    code.push_str("}\n\n");
    
    // Validate JSON against schema (simplified schema validation)
    code.push_str("// json.ValidateSchema - Validate JSON against schema\n");
    code.push_str("// Schema format: \"field1:type1,field2:type2,...\" or \"type\" for arrays\n");
    code.push_str("// Types: string, int, float, bool, array, object\n");
    code.push_str("// Returns: NULL if valid, error message if invalid\n");
    code.push_str("char* json_ValidateSchema(const char* json, const char* schema) {\n");
    code.push_str("    if (!json || !schema) return \"JSON error: null input\";\n");
    code.push_str("    \n");
    code.push_str("    // First validate JSON syntax\n");
    code.push_str("    char* syntax_err = json_Validate(json);\n");
    code.push_str("    if (syntax_err) return syntax_err;\n");
    code.push_str("    \n");
    code.push_str("    // If schema is empty or \"any\", accept any valid JSON\n");
    code.push_str("    if (!schema[0] || strcmp(schema, \"any\") == 0) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Check if JSON is an object\n");
    code.push_str("    int i = 0;\n");
    code.push_str("    while (json[i] == ' ' || json[i] == '\\t' || json[i] == '\\n' || json[i] == '\\r') i++;\n");
    code.push_str("    \n");
    code.push_str("    if (json[i] != '{') {\n");
    code.push_str("        return strdup(\"JSON schema error: expected object, got different type\");\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Parse schema: \"field1:type1,field2:type2\"\n");
    code.push_str("    // For each field in schema, check if it exists in JSON\n");
    code.push_str("    char* schema_copy = strdup(schema);\n");
    code.push_str("    if (!schema_copy) return \"JSON error: memory allocation failed\";\n");
    code.push_str("    \n");
    code.push_str("    char* token = strtok(schema_copy, \",\");\n");
    code.push_str("    while (token) {\n");
    code.push_str("        // Parse \"field:type\"\n");
    code.push_str("        char* colon = strchr(token, ':');\n");
    code.push_str("        if (!colon) {\n");
    code.push_str("            free(schema_copy);\n");
    code.push_str("            return strdup(\"JSON schema error: invalid schema format (expected 'field:type')\");\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        *colon = '\\0';\n");
    code.push_str("        char* field_name = token;\n");
    code.push_str("        char* field_type = colon + 1;\n");
    code.push_str("        \n");
    code.push_str("        // Check if field exists in JSON\n");
    code.push_str("        const char* field_value = json_GetObjectValue(json, field_name);\n");
    code.push_str("        if (!field_value) {\n");
    code.push_str("            char err_msg[256];\n");
    code.push_str("            snprintf(err_msg, sizeof(err_msg), \"JSON schema error: missing required field '%s'\", field_name);\n");
    code.push_str("            free(schema_copy);\n");
    code.push_str("            return strdup(err_msg);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Basic type checking (simplified)\n");
    code.push_str("        int i_val = 0;\n");
    code.push_str("        while (field_value[i_val] == ' ' || field_value[i_val] == '\\t' || field_value[i_val] == '\\n' || field_value[i_val] == '\\r') i_val++;\n");
    code.push_str("        \n");
    code.push_str("        if (strcmp(field_type, \"string\") == 0) {\n");
    code.push_str("            if (field_value[i_val] != '\\\"') {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON schema error: field '%s' should be string\", field_name);\n");
    code.push_str("                free(schema_copy);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (strcmp(field_type, \"int\") == 0 || strcmp(field_type, \"float\") == 0) {\n");
    code.push_str("            if ((field_value[i_val] < '0' || field_value[i_val] > '9') && field_value[i_val] != '-') {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON schema error: field '%s' should be number\", field_name);\n");
    code.push_str("                free(schema_copy);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (strcmp(field_type, \"bool\") == 0) {\n");
    code.push_str("            if (strncmp(field_value + i_val, \"true\", 4) != 0 && strncmp(field_value + i_val, \"false\", 5) != 0) {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON schema error: field '%s' should be boolean\", field_name);\n");
    code.push_str("                free(schema_copy);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (strcmp(field_type, \"array\") == 0) {\n");
    code.push_str("            if (field_value[i_val] != '[') {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON schema error: field '%s' should be array\", field_name);\n");
    code.push_str("                free(schema_copy);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        } else if (strcmp(field_type, \"object\") == 0) {\n");
    code.push_str("            if (field_value[i_val] != '{') {\n");
    code.push_str("                char err_msg[256];\n");
    code.push_str("                snprintf(err_msg, sizeof(err_msg), \"JSON schema error: field '%s' should be object\", field_name);\n");
    code.push_str("                free(schema_copy);\n");
    code.push_str("                return strdup(err_msg);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        token = strtok(NULL, \",\");\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    free(schema_copy);\n");
    code.push_str("    return NULL;  // Valid against schema\n");
    code.push_str("}\n\n");
    
    // ValidateStruct - Validate JSON against struct schema (uses generated function)
    code.push_str("// json.ValidateStruct - Validate JSON against struct schema\n");
    code.push_str("// This is a generic wrapper - actual validation uses compiler-generated functions\n");
    code.push_str("// Usage: json.ValidateStruct(json, \"StructName\") calls json_validate_structname(json)\n");
    code.push_str("// Note: The actual function name is generated by the compiler\n");
    code.push_str("char* json_ValidateStruct(const char* json, const char* struct_name) {\n");
    code.push_str("    if (!json || !struct_name) return \"JSON error: null input\";\n");
    code.push_str("    \n");
    code.push_str("    // Call compiler-generated validation function\n");
    code.push_str("    // Function name format: json_validate_<structname>\n");
    code.push_str("    // This is a simplified implementation - in practice, the compiler generates\n");
    code.push_str("    // a direct call to the specific validation function\n");
    code.push_str("    \n");
    code.push_str("    // For now, we'll use a generic approach\n");
    code.push_str("    // In a full implementation, this would dispatch to the correct function\n");
    code.push_str("    \n");
    code.push_str("    // First validate syntax\n");
    code.push_str("    char* syntax_err = json_Validate(json);\n");
    code.push_str("    if (syntax_err) return syntax_err;\n");
    code.push_str("    \n");
    code.push_str("    // Note: Struct-specific validation is done by compiler-generated functions\n");
    code.push_str("    // This function is a placeholder - actual validation happens at compile time\n");
    code.push_str("    return NULL;  // Valid (struct-specific checks done by generated code)\n");
    code.push_str("}\n\n");
    
    // MarshalSlice - Marshal slice/array to JSON array
    code.push_str("// json.MarshalSlice - Encode slice to JSON array string\n");
    code.push_str("// Note: Simplified - works with Slice* and element type string\n");
    code.push_str("char* json_MarshalSlice(Slice* slice, const char* elem_type) {\n");
    code.push_str("    static char buffer[8192];\n");
    code.push_str("    if (!slice || slice->len == 0) {\n");
    code.push_str("        return \"[]\";\n");
    code.push_str("    }\n");
    code.push_str("    strcpy(buffer, \"[\");\n");
    code.push_str("    for (int i = 0; i < slice->len; i++) {\n");
    code.push_str("        if (i > 0) strcat(buffer, \", \");\n");
    code.push_str("        // Simplified - assumes int elements for now\n");
    code.push_str("        char elem_str[64];\n");
    code.push_str("        if (strcmp(elem_type, \"int\") == 0) {\n");
    code.push_str("            int val = ((int*)slice->data)[i];\n");
    code.push_str("            snprintf(elem_str, sizeof(elem_str), \"%d\", val);\n");
    code.push_str("            strcat(buffer, elem_str);\n");
    code.push_str("        } else if (strcmp(elem_type, \"string\") == 0) {\n");
    code.push_str("            char* val = ((char**)slice->data)[i];\n");
    code.push_str("            strcat(buffer, json_escape(val));\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    strcat(buffer, \"]\");\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // MarshalStruct - Marshal struct to JSON object (simplified)
    code.push_str("// json.MarshalStruct - Encode struct to JSON object string\n");
    code.push_str("// Note: Simplified - requires manual field serialization\n");
    code.push_str("// This is a placeholder - full implementation would use reflection\n");
    code.push_str("char* json_MarshalStruct(const char* json_fields) {\n");
    code.push_str("    // json_fields should be pre-formatted as \"field1:value1,field2:value2\"\n");
    code.push_str("    static char buffer[8192];\n");
    code.push_str("    snprintf(buffer, sizeof(buffer), \"{%s}\", json_fields);\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // MarshalMap - Automatic map serialization
    code.push_str("// json.MarshalMap - Automatically encode map to JSON object string\n");
    code.push_str("char* json_MarshalMap(Map* m) {\n");
    code.push_str("    static char buffer[16384];\n");
    code.push_str("    if (!m || m->size == 0) {\n");
    code.push_str("        return \"{}\";\n");
    code.push_str("    }\n");
    code.push_str("    strcpy(buffer, \"{\");\n");
    code.push_str("    int first = 1;\n");
    code.push_str("    for (int i = 0; i < m->bucket_count; i++) {\n");
    code.push_str("        MapEntry* entry = m->buckets[i];\n");
    code.push_str("        while (entry) {\n");
    code.push_str("            if (!first) strcat(buffer, \", \");\n");
    code.push_str("            first = 0;\n");
    code.push_str("            \n");
    code.push_str("            // Serialize key\n");
    code.push_str("            if (m->key_type == 0) {  // string key\n");
    code.push_str("                char* key_str = *(char**)entry->key;\n");
    code.push_str("                strcat(buffer, json_escape(key_str));\n");
    code.push_str("            } else if (m->key_type == 1) {  // int key\n");
    code.push_str("                char key_str[64];\n");
    code.push_str("                snprintf(key_str, sizeof(key_str), \"\\\"%d\\\"\", *(int*)entry->key);\n");
    code.push_str("                strcat(buffer, key_str);\n");
    code.push_str("            } else {  // float key\n");
    code.push_str("                char key_str[64];\n");
    code.push_str("                snprintf(key_str, sizeof(key_str), \"\\\"%.6g\\\"\", *(double*)entry->key);\n");
    code.push_str("                strcat(buffer, key_str);\n");
    code.push_str("            }\n");
    code.push_str("            strcat(buffer, \":\");\n");
    code.push_str("            \n");
    code.push_str("            // Serialize value\n");
    code.push_str("            if (m->value_type == 0) {  // int value\n");
    code.push_str("                char val_str[64];\n");
    code.push_str("                snprintf(val_str, sizeof(val_str), \"%d\", *(int*)entry->value);\n");
    code.push_str("                strcat(buffer, val_str);\n");
    code.push_str("            } else if (m->value_type == 1) {  // float value\n");
    code.push_str("                char val_str[64];\n");
    code.push_str("                snprintf(val_str, sizeof(val_str), \"%.6g\", *(double*)entry->value);\n");
    code.push_str("                strcat(buffer, val_str);\n");
    code.push_str("            } else if (m->value_type == 2) {  // string value\n");
    code.push_str("                char* val_str = *(char**)entry->value;\n");
    code.push_str("                if (val_str) {\n");
    code.push_str("                    strcat(buffer, json_escape(val_str));\n");
    code.push_str("                } else {\n");
    code.push_str("                    strcat(buffer, \"null\");\n");
    code.push_str("                }\n");
    code.push_str("            } else {  // bool value\n");
    code.push_str("                strcat(buffer, *(int*)entry->value ? \"true\" : \"false\");\n");
    code.push_str("            }\n");
    code.push_str("            \n");
    code.push_str("            entry = entry->next;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    strcat(buffer, \"}\");\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // MarshalAny - Automatic serialization for any type
    code.push_str("// json.MarshalAny - Automatically marshal any value to JSON\n");
    code.push_str("// This function uses type information to automatically serialize structs, maps, slices\n");
    code.push_str("char* json_MarshalAny(const char* type_name, void* value) {\n");
    code.push_str("    // This is a dispatcher that calls appropriate marshal function\n");
    code.push_str("    // For structs, it calls json_marshal_<structname>\n");
    code.push_str("    // For slices, it calls json_MarshalSlice\n");
    code.push_str("    // For basic types, it calls json_Marshal\n");
    code.push_str("    static char buffer[16384];\n");
    code.push_str("    \n");
    code.push_str("    // Try to find struct marshal function\n");
    code.push_str("    // In a full implementation, we'd use function pointers or a lookup table\n");
    code.push_str("    // For now, return a placeholder\n");
    code.push_str("    snprintf(buffer, sizeof(buffer), \"{\\\"type\\\":\\\"%s\\\",\\\"value\\\":\\\"<auto>\\\"}\", type_name);\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    // Enhanced MarshalSlice with more type support
    code.push_str("// Enhanced json.MarshalSlice with float and bool support\n");
    code.push_str("char* json_MarshalSliceEnhanced(Slice* slice, const char* elem_type) {\n");
    code.push_str("    static char buffer[16384];\n");
    code.push_str("    if (!slice || slice->len == 0) {\n");
    code.push_str("        return \"[]\";\n");
    code.push_str("    }\n");
    code.push_str("    strcpy(buffer, \"[\");\n");
    code.push_str("    for (int i = 0; i < slice->len; i++) {\n");
    code.push_str("        if (i > 0) strcat(buffer, \", \");\n");
    code.push_str("        char elem_str[256];\n");
    code.push_str("        if (strcmp(elem_type, \"int\") == 0) {\n");
    code.push_str("            int val = ((int*)slice->data)[i];\n");
    code.push_str("            snprintf(elem_str, sizeof(elem_str), \"%d\", val);\n");
    code.push_str("            strcat(buffer, elem_str);\n");
    code.push_str("        } else if (strcmp(elem_type, \"float\") == 0) {\n");
    code.push_str("            double val = ((double*)slice->data)[i];\n");
    code.push_str("            snprintf(elem_str, sizeof(elem_str), \"%.6g\", val);\n");
    code.push_str("            strcat(buffer, elem_str);\n");
    code.push_str("        } else if (strcmp(elem_type, \"string\") == 0) {\n");
    code.push_str("            char* val = ((char**)slice->data)[i];\n");
    code.push_str("            if (val) {\n");
    code.push_str("                strcat(buffer, json_escape(val));\n");
    code.push_str("            } else {\n");
    code.push_str("                strcat(buffer, \"null\");\n");
    code.push_str("            }\n");
    code.push_str("        } else if (strcmp(elem_type, \"bool\") == 0) {\n");
    code.push_str("            int val = ((int*)slice->data)[i];\n");
    code.push_str("            strcat(buffer, val ? \"true\" : \"false\");\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    strcat(buffer, \"]\");\n");
    code.push_str("    return buffer;\n");
    code.push_str("}\n\n");
    
    code
}
