// net - Network utilities library
// Provides socket support, DNS resolution, and network operations

pub fn generate_net_lib() -> String {
    let mut code = String::new();
    
    // Platform detection and includes
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    #include <winsock2.h>\n");
    code.push_str("    #include <ws2tcpip.h>\n");
    code.push_str("    #pragma comment(lib, \"ws2_32.lib\")\n");
    code.push_str("    #define SHUT_RDWR SD_BOTH\n");
    code.push_str("#else\n");
    code.push_str("    #include <sys/socket.h>\n");
    code.push_str("    #include <netinet/in.h>\n");
    code.push_str("    #include <arpa/inet.h>\n");
    code.push_str("    #include <netdb.h>\n");
    code.push_str("    #include <unistd.h>\n");
    code.push_str("    #include <fcntl.h>\n");
    code.push_str("#endif\n");
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("#include <errno.h>\n");
    code.push_str("\n");
    code.push_str("static inline void net_sys_close(int sockfd) {\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    closesocket(sockfd);\n");
    code.push_str("#else\n");
    code.push_str("    close(sockfd);\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    code.push_str("// OpenSSL/TLS Support\n");
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("    #include <openssl/ssl.h>\n");
    code.push_str("    #include <openssl/err.h>\n");
    code.push_str("    #include <openssl/x509v3.h>\n");
    code.push_str("#endif\n");
    code.push_str("\n");
    
    // Initialize network library (Windows only)
    code.push_str("// net.Init - Initialize network library (Windows only)\n");
    code.push_str("int net_Init(void) {\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    WSADATA wsa;\n");
    code.push_str("    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {\n");
    code.push_str("        return -1;\n");
    code.push_str("    }\n");
    code.push_str("    return 0;\n");
    code.push_str("#else\n");
    code.push_str("    return 0;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // Cleanup network library (Windows only)
    code.push_str("// net.Cleanup - Cleanup network library (Windows only)\n");
    code.push_str("void net_Cleanup(void) {\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    WSACleanup();\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // DNS Resolution - Resolve hostname to IP address
    code.push_str("// net.ResolveHost - Resolve hostname to IP address\n");
    code.push_str("// Returns: IP address string (caller must free), or NULL on error\n");
    code.push_str("char* net_ResolveHost(const char* hostname) {\n");
    code.push_str("    if (!hostname) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    struct addrinfo hints, *result, *rp;\n");
    code.push_str("    memset(&hints, 0, sizeof(struct addrinfo));\n");
    code.push_str("    hints.ai_family = AF_INET;  // IPv4 only for now\n");
    code.push_str("    hints.ai_socktype = SOCK_STREAM;\n");
    code.push_str("    \n");
    code.push_str("    int status = getaddrinfo(hostname, NULL, &hints, &result);\n");
    code.push_str("    if (status != 0) {\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Get first IPv4 address\n");
    code.push_str("    char* ip = NULL;\n");
    code.push_str("    for (rp = result; rp != NULL; rp = rp->ai_next) {\n");
    code.push_str("        if (rp->ai_family == AF_INET) {\n");
    code.push_str("            struct sockaddr_in* addr = (struct sockaddr_in*)rp->ai_addr;\n");
    code.push_str("            ip = (char*)malloc(INET_ADDRSTRLEN);\n");
    code.push_str("            if (ip) {\n");
    code.push_str("                inet_ntop(AF_INET, &addr->sin_addr, ip, INET_ADDRSTRLEN);\n");
    code.push_str("            }\n");
    code.push_str("            break;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    freeaddrinfo(result);\n");
    code.push_str("    return ip;\n");
    code.push_str("}\n\n");
    
    // Create TCP socket
    code.push_str("// net.Dial - Create TCP connection to host:port\n");
    code.push_str("// Returns: Socket file descriptor, or -1 on error\n");
    code.push_str("int net_Dial(const char* host, int port) {\n");
    code.push_str("    if (!host) return -1;\n");
    code.push_str("    \n");
    code.push_str("    // Resolve hostname\n");
    code.push_str("    struct addrinfo hints, *result, *rp;\n");
    code.push_str("    memset(&hints, 0, sizeof(struct addrinfo));\n");
    code.push_str("    hints.ai_family = AF_INET;\n");
    code.push_str("    hints.ai_socktype = SOCK_STREAM;\n");
    code.push_str("    \n");
    code.push_str("    char port_str[16];\n");
    code.push_str("    snprintf(port_str, sizeof(port_str), \"%d\", port);\n");
    code.push_str("    \n");
    code.push_str("    int status = getaddrinfo(host, port_str, &hints, &result);\n");
    code.push_str("    if (status != 0) {\n");
    code.push_str("        return -1;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Try each address until we connect\n");
    code.push_str("    int sockfd = -1;\n");
    code.push_str("    for (rp = result; rp != NULL; rp = rp->ai_next) {\n");
    code.push_str("        sockfd = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);\n");
    code.push_str("        if (sockfd == -1) continue;\n");
    code.push_str("        \n");
    code.push_str("        if (connect(sockfd, rp->ai_addr, rp->ai_addrlen) == 0) {\n");
    code.push_str("            break;  // Success\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        net_sys_close(sockfd);\n");
    code.push_str("        sockfd = -1;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    freeaddrinfo(result);\n");
    code.push_str("    return sockfd;\n");
    code.push_str("}\n\n");
    
    // Send data
    code.push_str("// net.Send - Send data over socket\n");
    code.push_str("// Returns: Number of bytes sent, or -1 on error\n");
    code.push_str("int net_Send(int sockfd, const char* data, int len) {\n");
    code.push_str("    if (sockfd < 0 || !data || len < 0) return -1;\n");
    code.push_str("    return send(sockfd, data, len, 0);\n");
    code.push_str("}\n\n");
    
    // Receive data
    code.push_str("// net.Recv - Receive data from socket\n");
    code.push_str("// Returns: Number of bytes received, or -1 on error\n");
    code.push_str("// Note: buffer must be pre-allocated\n");
    code.push_str("int net_Recv(int sockfd, char* buffer, int len) {\n");
    code.push_str("    if (sockfd < 0 || !buffer || len < 0) return -1;\n");
    code.push_str("    return recv(sockfd, buffer, len, 0);\n");
    code.push_str("}\n\n");
    
    // Close socket
    code.push_str("// net.Close - Close socket\n");
    code.push_str("void net_Close(int sockfd) {\n");
    code.push_str("    if (sockfd >= 0) {\n");
    code.push_str("        net_sys_close(sockfd);\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
    
    // Listen on port
    code.push_str("// net.Listen - Listen on port\n");
    code.push_str("// Returns: Socket file descriptor, or -1 on error\n");
    code.push_str("int net_Listen(int port) {\n");
    code.push_str("    int sockfd = socket(AF_INET, SOCK_STREAM, 0);\n");
    code.push_str("    if (sockfd < 0) return -1;\n");
    code.push_str("    \n");
    code.push_str("    // Set socket options (reuse address)\n");
    code.push_str("    int opt = 1;\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, (char*)&opt, sizeof(opt));\n");
    code.push_str("#else\n");
    code.push_str("    setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));\n");
    code.push_str("#endif\n");
    code.push_str("    \n");
    code.push_str("    // Bind to port\n");
    code.push_str("    struct sockaddr_in addr;\n");
    code.push_str("    memset(&addr, 0, sizeof(addr));\n");
    code.push_str("    addr.sin_family = AF_INET;\n");
    code.push_str("    addr.sin_addr.s_addr = INADDR_ANY;\n");
    code.push_str("    addr.sin_port = htons(port);\n");
    code.push_str("    \n");
    code.push_str("    if (bind(sockfd, (struct sockaddr*)&addr, sizeof(addr)) < 0) {\n");
    code.push_str("        net_sys_close(sockfd);\n");
    code.push_str("        return -1;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Listen\n");
    code.push_str("    if (listen(sockfd, 10) < 0) {\n");
    code.push_str("        net_sys_close(sockfd);\n");
    code.push_str("        return -1;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return sockfd;\n");
    code.push_str("}\n\n");
    
    // Accept connection
    code.push_str("// net.Accept - Accept incoming connection\n");
    code.push_str("// Returns: Socket file descriptor for new connection, or -1 on error\n");
    code.push_str("int net_Accept(int listenfd) {\n");
    code.push_str("    if (listenfd < 0) return -1;\n");
    code.push_str("    struct sockaddr_in client_addr;\n");
    code.push_str("    socklen_t addr_len = sizeof(client_addr);\n");
    code.push_str("    return accept(listenfd, (struct sockaddr*)&client_addr, &addr_len);\n");
    code.push_str("}\n\n");
    
    // TLS/SSL Support Functions
    code.push_str("#ifdef USE_OPENSSL\n");
    code.push_str("// TLS Context structure (opaque pointer)\n");
    code.push_str("typedef struct {\n");
    code.push_str("    SSL_CTX* ctx;\n");
    code.push_str("} TLSContext;\n\n");
    code.push_str("// TLS Connection structure\n");
    code.push_str("typedef struct {\n");
    code.push_str("    int sockfd;\n");
    code.push_str("    SSL* ssl;\n");
    code.push_str("} TLSConnection;\n\n");
    code.push_str("// net.TLSInit - Initialize TLS/SSL library\n");
    code.push_str("// Returns: 0 on success, -1 on error\n");
    code.push_str("int net_TLSInit(void) {\n");
    code.push_str("    SSL_library_init();\n");
    code.push_str("    SSL_load_error_strings();\n");
    code.push_str("    OpenSSL_add_all_algorithms();\n");
    code.push_str("    return 0;\n");
    code.push_str("}\n\n");
    code.push_str("// net.TLSCleanup - Cleanup TLS/SSL library\n");
    code.push_str("void net_TLSCleanup(void) {\n");
    code.push_str("    EVP_cleanup();\n");
    code.push_str("}\n\n");
    code.push_str("// net.TLSDial - Create TLS connection to host:port\n");
    code.push_str("// Returns: TLS connection handle (void*), or NULL on error\n");
    code.push_str("// Caller must free with net_TLSClose()\n");
    code.push_str("void* net_TLSDial(const char* host, int port) {\n");
    code.push_str("    if (!host) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Create SSL context\n");
    code.push_str("    SSL_CTX* ctx = SSL_CTX_new(TLS_client_method());\n");
    code.push_str("    if (!ctx) return NULL;\n");
    code.push_str("    \n");
    code.push_str("    // Enable certificate verification\n");
    code.push_str("    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, NULL);\n");
    code.push_str("    \n");
    code.push_str("    // Load default certificate store\n");
    code.push_str("    if (SSL_CTX_set_default_verify_paths(ctx) != 1) {\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Create TCP connection first\n");
    code.push_str("    int sockfd = net_Dial(host, port);\n");
    code.push_str("    if (sockfd < 0) {\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Create SSL connection\n");
    code.push_str("    SSL* ssl = SSL_new(ctx);\n");
    code.push_str("    if (!ssl) {\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Attach socket to SSL\n");
    code.push_str("    SSL_set_fd(ssl, sockfd);\n");
    code.push_str("    \n");
    code.push_str("    // Set hostname for SNI (Server Name Indication)\n");
    code.push_str("    SSL_set_tlsext_host_name(ssl, host);\n");
    code.push_str("    \n");
    code.push_str("    // Perform TLS handshake\n");
    code.push_str("    if (SSL_connect(ssl) <= 0) {\n");
    code.push_str("        SSL_free(ssl);\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Verify certificate\n");
    code.push_str("    X509* cert = SSL_get_peer_certificate(ssl);\n");
    code.push_str("    if (!cert) {\n");
    code.push_str("        SSL_free(ssl);\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    long verify_result = SSL_get_verify_result(ssl);\n");
    code.push_str("    X509_free(cert);\n");
    code.push_str("    if (verify_result != X509_V_OK) {\n");
    code.push_str("        SSL_free(ssl);\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Allocate TLS connection structure\n");
    code.push_str("    TLSConnection* tls_conn = (TLSConnection*)malloc(sizeof(TLSConnection));\n");
    code.push_str("    if (!tls_conn) {\n");
    code.push_str("        SSL_free(ssl);\n");
    code.push_str("        net_Close(sockfd);\n");
    code.push_str("        SSL_CTX_free(ctx);\n");
    code.push_str("        return NULL;\n");
    code.push_str("    }\n");
    code.push_str("    tls_conn->sockfd = sockfd;\n");
    code.push_str("    tls_conn->ssl = ssl;\n");
    code.push_str("    \n");
    code.push_str("    // Store context for cleanup\n");
    code.push_str("    // Note: In production, you might want to reuse SSL_CTX\n");
    code.push_str("    \n");
    code.push_str("    return (void*)tls_conn;\n");
    code.push_str("}\n\n");
    code.push_str("// net.TLSSend - Send data over TLS connection\n");
    code.push_str("// Returns: Number of bytes sent, or -1 on error\n");
    code.push_str("int net_TLSSend(void* tls_conn, const char* data, int len) {\n");
    code.push_str("    if (!tls_conn || !data || len < 0) return -1;\n");
    code.push_str("    TLSConnection* conn = (TLSConnection*)tls_conn;\n");
    code.push_str("    return SSL_write(conn->ssl, data, len);\n");
    code.push_str("}\n\n");
    code.push_str("// net.TLSRecv - Receive data from TLS connection\n");
    code.push_str("// Returns: Number of bytes received, or -1 on error\n");
    code.push_str("int net_TLSRecv(void* tls_conn, char* buffer, int len) {\n");
    code.push_str("    if (!tls_conn || !buffer || len < 0) return -1;\n");
    code.push_str("    TLSConnection* conn = (TLSConnection*)tls_conn;\n");
    code.push_str("    return SSL_read(conn->ssl, buffer, len);\n");
    code.push_str("}\n\n");
    code.push_str("// net.TLSClose - Close TLS connection\n");
    code.push_str("void net_TLSClose(void* tls_conn) {\n");
    code.push_str("    if (!tls_conn) return;\n");
    code.push_str("    TLSConnection* conn = (TLSConnection*)tls_conn;\n");
    code.push_str("    if (conn->ssl) {\n");
    code.push_str("        SSL_shutdown(conn->ssl);\n");
    code.push_str("        SSL_free(conn->ssl);\n");
    code.push_str("    }\n");
    code.push_str("    if (conn->sockfd >= 0) {\n");
    code.push_str("        net_Close(conn->sockfd);\n");
    code.push_str("    }\n");
    code.push_str("    free(tls_conn);\n");
    code.push_str("}\n\n");
    code.push_str("#else\n");
    code.push_str("// TLS functions stubs when OpenSSL is not available\n");
    code.push_str("int net_TLSInit(void) { return -1; }\n");
    code.push_str("void net_TLSCleanup(void) {}\n");
    code.push_str("void* net_TLSDial(const char* host, int port) { (void)host; (void)port; return NULL; }\n");
    code.push_str("int net_TLSSend(void* tls_conn, const char* data, int len) { (void)tls_conn; (void)data; (void)len; return -1; }\n");
    code.push_str("int net_TLSRecv(void* tls_conn, char* buffer, int len) { (void)tls_conn; (void)buffer; (void)len; return -1; }\n");
    code.push_str("void net_TLSClose(void* tls_conn) { (void)tls_conn; }\n");
    code.push_str("#endif\n\n");
    
    code
}
