// regexp - Regular Expressions library
// Ported from Go's regexp package

pub fn generate_regexp_lib() -> String {
    let mut code = String::new();
    
    // Include necessary headers
    code.push_str("#include <stdio.h>\n");
    code.push_str("#include <stdlib.h>\n");
    code.push_str("#include <string.h>\n");
    code.push_str("#ifndef _WIN32\n");
    code.push_str("#include <regex.h>\n");
    code.push_str("#endif\n");
    code.push_str("\n");
    
    // Helper function to compile regex pattern
    code.push_str("#ifndef _WIN32\n");
    code.push_str("static int compile_regex(regex_t* regex, const char* pattern) {\n");
    code.push_str("    int ret = regcomp(regex, pattern, REG_EXTENDED);\n");
    code.push_str("    if (ret != 0) {\n");
    code.push_str("        return 0; // Failed to compile\n");
    code.push_str("    }\n");
    code.push_str("    return 1; // Success\n");
    code.push_str("}\n");
    code.push_str("#endif\n\n");
    
    // Match - Check if pattern matches
    code.push_str("// regexp.Match - Check if pattern matches\n");
    code.push_str("int regexp_Match(const char* pattern, const char* text) {\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    return 0; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        return 0; // Invalid pattern\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    int ret = regexec(&regex, text, 0, NULL, 0);\n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    \n");
    code.push_str("    return (ret == 0) ? 1 : 0; // 1 = match, 0 = no match\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // Find - Find first match
    code.push_str("// regexp.Find - Find first match\n");
    code.push_str("char* regexp_Find(const char* pattern, const char* text) {\n");
    code.push_str("    static char result[1024];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    return result; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    \n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        return result; // Invalid pattern\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regmatch_t matches[1];\n");
    code.push_str("    int ret = regexec(&regex, text, 1, matches, 0);\n");
    code.push_str("    \n");
    code.push_str("    if (ret == 0 && matches[0].rm_so >= 0) {\n");
    code.push_str("        int start = matches[0].rm_so;\n");
    code.push_str("        int end = matches[0].rm_eo;\n");
    code.push_str("        int len = end - start;\n");
    code.push_str("        if (len > 0 && len < sizeof(result)) {\n");
    code.push_str("            strncpy(result, text + start, len);\n");
    code.push_str("            result[len] = '\\0';\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    return result;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // FindAll - Find all matches (returns newline-separated string)
    code.push_str("// regexp.FindAll - Find all matches (returns newline-separated string)\n");
    code.push_str("char* regexp_FindAll(const char* pattern, const char* text, int maxMatches) {\n");
    code.push_str("    static char result[8192]; // 8KB buffer\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    return result; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    \n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        return result; // Invalid pattern\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regmatch_t matches[1];\n");
    code.push_str("    const char* search_start = text;\n");
    code.push_str("    int match_count = 0;\n");
    code.push_str("    \n");
    code.push_str("    while (match_count < maxMatches && *search_start) {\n");
    code.push_str("        int ret = regexec(&regex, search_start, 1, matches, 0);\n");
    code.push_str("        if (ret != 0) break; // No more matches\n");
    code.push_str("        \n");
    code.push_str("        int start = matches[0].rm_so;\n");
    code.push_str("        int end = matches[0].rm_eo;\n");
    code.push_str("        if (start < 0 || end <= start) break;\n");
    code.push_str("        \n");
    code.push_str("        int len = end - start;\n");
    code.push_str("        int current_len = strlen(result);\n");
    code.push_str("        \n");
    code.push_str("        if (current_len + len + 2 < sizeof(result)) {\n");
    code.push_str("            if (current_len > 0) strcat(result, \"\\n\");\n");
    code.push_str("            strncat(result, search_start + start, len);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Move search start past this match\n");
    code.push_str("        search_start += end;\n");
    code.push_str("        match_count++;\n");
    code.push_str("        \n");
    code.push_str("        // Avoid infinite loop on zero-length matches\n");
    code.push_str("        if (len == 0) search_start++;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    return result;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // Replace - Replace first match
    code.push_str("// regexp.Replace - Replace first match\n");
    code.push_str("char* regexp_Replace(const char* pattern, const char* text, const char* repl) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("    result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    return result; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    \n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("        return result; // Invalid pattern, return original\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regmatch_t matches[1];\n");
    code.push_str("    int ret = regexec(&regex, text, 1, matches, 0);\n");
    code.push_str("    \n");
    code.push_str("    if (ret == 0 && matches[0].rm_so >= 0) {\n");
    code.push_str("        int start = matches[0].rm_so;\n");
    code.push_str("        int end = matches[0].rm_eo;\n");
    code.push_str("        \n");
    code.push_str("        // Copy part before match\n");
    code.push_str("        if (start > 0) {\n");
    code.push_str("            strncat(result, text, start);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Add replacement\n");
    code.push_str("        strcat(result, repl);\n");
    code.push_str("        \n");
    code.push_str("        // Copy part after match\n");
    code.push_str("        int text_len = strlen(text);\n");
    code.push_str("        if (end < text_len) {\n");
    code.push_str("            strcat(result, text + end);\n");
    code.push_str("        }\n");
    code.push_str("    } else {\n");
    code.push_str("        // No match, return original\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    return result;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // ReplaceAll - Replace all matches
    code.push_str("// regexp.ReplaceAll - Replace all matches\n");
    code.push_str("char* regexp_ReplaceAll(const char* pattern, const char* text, const char* repl) {\n");
    code.push_str("    static char result[4096];\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("    result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    return result; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    static char temp[4096];\n");
    code.push_str("    \n");
    code.push_str("    strncpy(temp, text, sizeof(temp) - 1);\n");
    code.push_str("    temp[sizeof(temp) - 1] = '\\0';\n");
    code.push_str("    \n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("        return result; // Invalid pattern\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("    regmatch_t matches[1];\n");
    code.push_str("    const char* search_start = temp;\n");
    code.push_str("    int last_end = 0;\n");
    code.push_str("    \n");
    code.push_str("    while (*search_start) {\n");
    code.push_str("        int ret = regexec(&regex, search_start, 1, matches, 0);\n");
    code.push_str("        if (ret != 0) break; // No more matches\n");
    code.push_str("        \n");
    code.push_str("        int start = matches[0].rm_so;\n");
    code.push_str("        int end = matches[0].rm_eo;\n");
    code.push_str("        if (start < 0 || end <= start) break;\n");
    code.push_str("        \n");
    code.push_str("        int current_len = strlen(result);\n");
    code.push_str("        int text_pos = search_start - temp + start;\n");
    code.push_str("        \n");
    code.push_str("        // Copy part before match\n");
    code.push_str("        if (text_pos > last_end) {\n");
    code.push_str("            int len = text_pos - last_end;\n");
    code.push_str("            if (current_len + len < sizeof(result) - 1) {\n");
    code.push_str("                strncat(result, temp + last_end, len);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        // Add replacement\n");
    code.push_str("        if (current_len + strlen(repl) < sizeof(result) - 1) {\n");
    code.push_str("            strcat(result, repl);\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        last_end = text_pos + (end - start);\n");
    code.push_str("        search_start += end;\n");
    code.push_str("        \n");
    code.push_str("        // Avoid infinite loop on zero-length matches\n");
    code.push_str("        if (end == start) search_start++;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Copy remaining text\n");
    code.push_str("    int text_len = strlen(temp);\n");
    code.push_str("    if (last_end < text_len) {\n");
    code.push_str("        strcat(result, temp + last_end);\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    \n");
    code.push_str("    // If no matches, return original\n");
    code.push_str("    if (strlen(result) == 0) {\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    return result;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    // Split - Split by pattern (returns newline-separated string)
    code.push_str("// regexp.Split - Split by pattern (returns newline-separated string)\n");
    code.push_str("char* regexp_Split(const char* pattern, const char* text) {\n");
    code.push_str("    static char result[8192]; // 8KB buffer\n");
    code.push_str("    result[0] = '\\0';\n");
    code.push_str("#ifdef _WIN32\n");
    code.push_str("    strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("    result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    return result; // Not supported on Windows\n");
    code.push_str("#else\n");
    code.push_str("    \n");
    code.push_str("    regex_t regex;\n");
    code.push_str("    if (!compile_regex(&regex, pattern)) {\n");
    code.push_str("        // Invalid pattern, return original text\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("        return result;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regmatch_t matches[1];\n");
    code.push_str("    const char* search_start = text;\n");
    code.push_str("    int last_end = 0;\n");
    code.push_str("    \n");
    code.push_str("    while (*search_start) {\n");
    code.push_str("        int ret = regexec(&regex, search_start, 1, matches, 0);\n");
    code.push_str("        if (ret != 0) break; // No more matches\n");
    code.push_str("        \n");
    code.push_str("        int start = matches[0].rm_so;\n");
    code.push_str("        int end = matches[0].rm_eo;\n");
    code.push_str("        if (start < 0 || end <= start) break;\n");
    code.push_str("        \n");
    code.push_str("        int text_pos = search_start - text + start;\n");
    code.push_str("        int current_len = strlen(result);\n");
    code.push_str("        \n");
    code.push_str("        // Add part before match\n");
    code.push_str("        if (text_pos > last_end) {\n");
    code.push_str("            int len = text_pos - last_end;\n");
    code.push_str("            if (current_len + len + 2 < sizeof(result)) {\n");
    code.push_str("                if (current_len > 0) strcat(result, \"\\n\");\n");
    code.push_str("                strncat(result, text + last_end, len);\n");
    code.push_str("            }\n");
    code.push_str("        }\n");
    code.push_str("        \n");
    code.push_str("        last_end = text_pos + (end - start);\n");
    code.push_str("        search_start += end;\n");
    code.push_str("        \n");
    code.push_str("        // Avoid infinite loop on zero-length matches\n");
    code.push_str("        if (end == start) search_start++;\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // Add remaining text\n");
    code.push_str("    int text_len = strlen(text);\n");
    code.push_str("    if (last_end < text_len) {\n");
    code.push_str("        int current_len = strlen(result);\n");
    code.push_str("        int len = text_len - last_end;\n");
    code.push_str("        if (current_len + len + 2 < sizeof(result)) {\n");
    code.push_str("            if (current_len > 0) strcat(result, \"\\n\");\n");
    code.push_str("            strcat(result, text + last_end);\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    // If no matches, return original text\n");
    code.push_str("    if (strlen(result) == 0) {\n");
    code.push_str("        strncpy(result, text, sizeof(result) - 1);\n");
    code.push_str("        result[sizeof(result) - 1] = '\\0';\n");
    code.push_str("    }\n");
    code.push_str("    \n");
    code.push_str("    regfree(&regex);\n");
    code.push_str("    return result;\n");
    code.push_str("#endif\n");
    code.push_str("}\n\n");
    
    code
}
